const root=document.getElementById('root');
let token=localStorage.getItem('onehms_token')||'';let me=null;let page='dashboard';
const pageModule={dashboard:'reports',patients:'patients',reception:'reception',appointments:'appointments',encounters:'opd',laboratory:'laboratory',pharmacy:'pharmacy',billing:'billing',inventory:'inventory',inpatient:'wards',staff:'users',reports:'reports',audit:'audit',modules:'configuration'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>'TZS '+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
function sparkSVG(values,w=130,h=32){const max=Math.max(1,...values),min=Math.min(0,...values),span=max-min||1;const pts=values.map((v,i)=>`${(i/(Math.max(values.length-1,1))*w).toFixed(1)},${(h-3-((v-min)/span)*(h-6)).toFixed(1)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" width="${w}" height="${h}" style="display:block"><polyline fill="none" stroke="var(--accent)" stroke-width="2" stroke-linejoin="round" points="${pts}"/></svg>`}
function barSVG(labels,values,w=280,h=120,barColor='var(--primary)',gap=6){const max=Math.max(1,...values);const bw=Math.max(8,Math.floor((w-gap*(values.length+1))/values.length));const bars=values.map((v,i)=>{const bh=Math.max(1,(v/max)*(h-16));const x=gap+(bw+gap)*i;return `<rect x="${x}" y="${h-4-bh}" width="${bw}" height="${bh}" rx="3" fill="${barColor}" opacity=".85"/><text x="${x+bw/2}" y="${h-8-bh}" text-anchor="middle" fill="var(--muted)" font-size="9" font-weight="700">${v}</text><text x="${x+bw/2}" y="${h+2}" text-anchor="middle" fill="var(--muted)" font-size="8">${labels[i]||''}</text>`}).join(' ');return `<svg viewBox="0 0 ${w} ${h+12}" preserveAspectRatio="xMidYMid meet" width="${w}" height="${h+12}" style="display:block">${bars}</svg>`}
const icon={dashboard:'▦',patients:'◎',reception:'⌂',appointments:'◷',encounters:'+',laboratory:'⌁',pharmacy:'✚',billing:'$',inventory:'▣',inpatient:'▥',operations:'◇',staff:'♙',reports:'▤',audit:'≡',modules:'⚙'};
const BELL_SVG='<svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>';
document.addEventListener('click',e=>{if(!e.target.closest('.topSearch')){const d=document.getElementById('searchDrop');if(d&&!d.contains(e.target))d.textContent=''}if(!e.target.closest('#bellBtn')&&!e.target.closest('#bellDrop'))document.getElementById('bellDrop')?.classList.remove('open')});
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h});const b=await r.json().catch(()=>({}));if(r.status===401){token='';localStorage.removeItem('onehms_token')}if(!r.ok){const code=b.detail?.code;const m=code&&friendlyErrors[code]?friendlyErrors[code]:(typeof b.detail==='string'?b.detail:(code||JSON.stringify(b.detail)||'Request failed'));throw new Error(m)}return b}
const friendlyErrors={MODULE_DISABLED:'Moduli hii haijawashwa na hospitali yako. This module is not enabled.',PERMISSION_DENIED:'Huna ruhusa ya kufanya hatua hii. You are not permitted to perform this action.'};
async function openTokenHTML(path){const r=await fetch(path,{headers:{Authorization:'Bearer '+token}});if(r.status===401){token='';localStorage.removeItem('onehms_token');renderLogin();return}if(!r.ok)throw new Error('Request failed');const w=window.open('','_blank');if(!w)throw new Error('Pop-up blocked');w.document.write(await r.text());w.document.close()}
function downloadTokenCSV(path,filename){fetch(path,{headers:{Authorization:'Bearer '+token}}).then(r=>{if(r.status===401){token='';localStorage.removeItem('onehms_token');renderLogin();return}if(!r.ok)throw new Error('Export failed');return r.text()}).then(text=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=filename;a.click()}).catch(e=>toast(e.message))}
let roleMeta=null,roleMetaPromise=null;let patientRowsCache=null;const CAT_COLORS={'System & Management':'#0F6E56','Front Office':'#2563EB','Clinical':'#D97706','Nursing':'#7C3AED','Theatre':'#DC2626','Laboratory':'#0891B2','Pharmacy':'#16A34A','Radiology':'#0284C7','Finance':'#059669','Inventory & Procurement':'#9333EA','Administration':'#57534E','Other Hospital Services':'#EA580C','Specialty Clinical':'#C026D3'};
async function getRoleMeta(){if(roleMeta)return roleMeta;if(!roleMetaPromise)roleMetaPromise=api('/api/role-templates').then(t=>{roleMeta={};t.forEach(x=>{if(!roleMeta[x.name])roleMeta[x.name]=x});return roleMeta}).catch(()=>{roleMeta=roleMeta||{};return roleMeta});return roleMetaPromise}
function hexA(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
function roleCat(category){if(!category)return '';const c=CAT_COLORS[category]||'#6B7280';return `<span class="roleCat" style="color:${c};background:${hexA(c,.12)}">${esc(category)}</span>`}
function can(mod,action='VIEW'){if(!me?.modules?.[mod])return false;const p=me.permissions?.[mod]||[];return p.includes('*')||p.includes(action)}
function hasSpecialistAccess(){return Object.entries(me?.modules||{}).some(([k,enabled])=>enabled&&!['wards','beds'].includes(k)&&!['patients','medical_records','reception','appointments','opd','triage','consultation','diagnosis','prescriptions','pharmacy','laboratory','billing','inventory','reports','users','audit','configuration'].includes(k)&&can(k,'VIEW'))}
function firstAccessiblePage(){const order=['dashboard','patients','reception','appointments','encounters','laboratory','pharmacy','billing','inventory','inpatient','operations','staff','reports','audit','modules'];return order.find(p=>p==='operations'?hasSpecialistAccess():can(pageModule[p]))||null}
function field(label,input){return `<label class="field"><span>${label}</span>${input}</label>`}
function badge(v){return `<span class="badge badge-${esc(String(v).toLowerCase())}">${esc(v)}</span>`}
function btn(text,id,style=false){const cls=(style===true)?'ghost':((typeof style==='string'&&style)?style:'primary');return `<button id="${id}" class="${cls}">${text}</button>`}
function patientOptions(rows,selected=''){return `<option value="">Select patient</option>`+rows.map(p=>`<option value="${p.id}" ${String(p.id)===String(selected)?'selected':''}>${esc(p.patient_no)} — ${esc(p.first_name)} ${esc(p.last_name)}</option>`).join('')}
function modal(title,body){const wrap=document.createElement('div');wrap.className='modalBackdrop';wrap.innerHTML=`<div class="modal wide" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modalHead"><h2>${title}</h2><button class="iconBtn" data-close aria-label="Close dialog">×</button></div>${body}</div>`;document.body.appendChild(wrap);wrap.querySelector('[data-close]').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};const onKey=e=>{if(e.key==='Escape'){wrap.remove();document.removeEventListener('keydown',onKey)}};document.addEventListener('keydown',onKey);return wrap}
function shell(content){
  const nav=[['dashboard','Dashboard','reports'],['patients','Patients','patients'],['reception','Reception','reception'],['appointments','Appointments','appointments'],['encounters','OPD & Consultation','opd'],['laboratory','Laboratory','laboratory'],['pharmacy','Pharmacy','pharmacy'],['billing','Billing','billing'],['inventory','Inventory','inventory'],['inpatient','Inpatient & Beds','wards'],['operations','Specialist Modules',null],['staff','Users & Roles','users'],['reports','Reports','reports'],['audit','Audit Log','audit'],['modules','Configuration','configuration']].filter(([id,,m])=>id==='operations'?hasSpecialistAccess():(!m||can(m)));
  const current=nav.find(([id])=>id===page)?.[1]||'Dashboard';
  const searchable=can('patients');
  root.innerHTML=`<div class="appShell"><div class="sidebarOverlay" id="sidebarOverlay"></div><aside class="sidebar" id="sidebar"><div class="sideBrand"><div class="brandMark small">+</div><div><b>One HMS</b><span>${esc(me.hospital.name)}</span></div><button class="closeMob" id="closeNav" aria-label="Close navigation">×</button></div><nav>${nav.map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}"><span class="navIcon">${icon[id]}</span><span>${label}</span></button>`).join('')}</nav><div class="userBox"><div class="avatar">${esc(me.full_name[0])}</div><div><b>${esc(me.full_name)}</b><span>${esc(me.role)}</span></div></div></aside><main><div class="topBar"><div class="topBarLeft"><button class="mobileMenuBtn" id="openNav" aria-label="Open navigation">☰</button><div class="brandMark mini">+</div><div class="topBarTitle"><b>${esc(current)}</b><span>${esc(me.hospital.name)}</span></div></div>${searchable?`<div class="topSearch"><input id="topSearch" placeholder="Search patient · name, ID or phone" autocomplete="off" aria-label="Quick patient search"><div class="searchDrop" id="searchDrop"></div></div>`:''}<div class="topBarRight"><button class="bellBtn" id="bellBtn" aria-label="Notifications">${BELL_SVG}<span class="bellDot" id="bellDot"></span></button><div class="bellDrop" id="bellDrop"></div><span data-rolecat></span><div class="topAvatar avatar" title="${esc(me.full_name)}">${esc(me.full_name[0])}</div><button class="iconBtn logoutBtn" id="logout" aria-label="Sign out" title="Sign out">↪</button></div></div><div class="content">${content}</div></main></div>`;
  const side=root.querySelector('#sidebar'),overlay=root.querySelector('#sidebarOverlay');
  const closeNav=()=>{side?.classList.remove('mobileOpen');overlay?.classList.remove('show')};
  const openNav=()=>{side?.classList.add('mobileOpen');overlay?.classList.add('show')};
  root.querySelector('#openNav')?.addEventListener('click',openNav);root.querySelector('#closeNav')?.addEventListener('click',closeNav);overlay?.addEventListener('click',closeNav);
  root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;closeNav();render()});
  document.getElementById('logout').onclick=()=>{token='';localStorage.removeItem('onehms_token');me=null;renderLogin()}
  if(searchable)bindTopSearch();
  bindBell();
  getRoleMeta().then(meta=>{const cat=meta?.[me.role]?.category;if(!cat)return;root.querySelectorAll('[data-rolecat]').forEach(el=>el.innerHTML=roleCat(cat))});
}
async function patientCache(){patientRowsCache=patientRowsCache||await api('/api/patients');return patientRowsCache}
function bindTopSearch(){
  const box=document.getElementById('topSearch'),drop=document.getElementById('searchDrop');let t;
  const run=()=>{clearTimeout(t);t=setTimeout(()=>showSearch(drop,box.value),140)};
  box.addEventListener('input',run);box.addEventListener('focus',run);
  box.addEventListener('keydown',e=>{if(e.key==='Enter'){page='patients';render()}if(e.key==='Escape'){drop.innerHTML='';box.blur()}});
}
async function showSearch(drop,q){
  q=(q||'').trim().toLowerCase();
  if(!q){drop.innerHTML='';return}
  try{
    const rows=await patientCache();
    const hits=rows.filter(p=>`${p.patient_no} ${p.first_name} ${p.last_name} ${p.phone||''} ${p.nida||''}`.toLowerCase().includes(q)).slice(0,6);
    drop.innerHTML=`${hits.map(p=>`<button class="searchHit" data-patient="${p.id}"><b>${esc(p.patient_no)}</b><span>${esc(p.first_name)} ${esc(p.last_name)}</span><small>${esc(p.phone||'')}</small></button>`).join('')||'<div class="empty">No patients match</div>'}<button class="searchHit searchAll" data-nav="patients"><b>Open Patients page →</b></button>`;
    drop.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>openPatient(b.dataset.patient));
    drop.querySelector('[data-nav]')?.addEventListener('click',()=>{page='patients';render()});
  }catch(e){drop.innerHTML='<div class="empty">Search unavailable</div>'}
}
function bindBell(){
  const btn=document.getElementById('bellBtn'),dot=document.getElementById('bellDot'),drop=document.getElementById('bellDrop');let cache=null;
  const closeBell=()=>drop.classList.remove('open');
  btn.addEventListener('click',async e=>{
    e.stopPropagation();
    if(drop.classList.contains('open')){closeBell();return}
    drop.classList.add('open');
    if(!cache){try{cache=await api('/api/dashboard/role')}catch(_){cache={alerts:[]}}}
    const alerts=cache.alerts||[];
    drop.innerHTML=`<div class="bellHead">Notifications</div>${alerts.map(a=>`<div class="bellItem bell-${a.level==='danger'?'danger':'warn'}"><b>${esc(a.title)}</b><span>${esc(a.detail)}</span></div>`).join('')||'<div class="bellItem"><span>No alerts</span></div>'}`;
  });
  api('/api/dashboard/role').then(d=>{const n=(d.alerts||[]).length;if(n>0){dot.style.display='grid';dot.textContent=n}}).catch(()=>{});
}
function header(title,sub,action=''){return `<div class="pageHeader"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function table(headers,rows){return `<div class="panel tableWrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>${rows.length?'':'<div class="empty">No records found</div>'}</div>`}

function renderLogin(){
  root.innerHTML=`<div class="loginShell"><section class="loginVisual"><div class="loginVisualContent"><div class="brandRow"><div class="brandMark small">+</div><span>One HMS</span></div><h2>Hospital operations, kept clear and connected.</h2><p>A secure modular workspace for patient care, clinical teams, pharmacy, laboratory, billing and hospital administration.</p></div><div class="loginProof"><div><b>Role-based access</b><span>Permissions by responsibility</span></div><div><b>Modular services</b><span>Configured per facility</span></div><div><b>Audit-ready</b><span>Operational activity history</span></div></div></section><div class="loginFormWrap"><form id="login" class="loginCard"><div class="loginMobileBrand"><div class="brandMark">+</div><b>One HMS</b></div><h1>Welcome back</h1><p>Sign in to your hospital workspace.</p>${field('Email','<input id="email" type="email" autocomplete="username" value="admin@onehms.com" required>')}${field('Password','<input id="password" type="password" autocomplete="current-password" value="Admin123!" required>')}<div id="loginErr"></div>${btn('Sign in','loginBtn')}<small>Demo administrator: admin@onehms.com · Admin123!</small></form></div></div>`;
  document.getElementById('login').onsubmit=async e=>{e.preventDefault();const submit=document.getElementById('loginBtn');submit.disabled=true;submit.textContent='Signing in…';try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('email').value,password:document.getElementById('password').value})});token=d.access_token;localStorage.setItem('onehms_token',token);me=await api('/api/me');render()}catch(x){document.getElementById('loginErr').innerHTML=`<div class="error">${esc(x.message)}</div>`;submit.disabled=false;submit.textContent='Sign in'}}
}
async function render(){
  if(!token)return renderLogin();
  try{
    // Refresh effective hospital configuration before every screen transition.
    // This ensures a module disabled by an administrator in another session is
    // removed from navigation and access immediately on the user's next action.
    me=await api('/api/me');
    const required=pageModule[page];
    if((required&&!can(required))||(page==='operations'&&!hasSpecialistAccess())){
      page=firstAccessiblePage();
      if(!page){root.innerHTML='<div class="loginShell"><div class="loginCard"><h1>No enabled workspace</h1><p>Your account has no VIEW access to an enabled hospital module. Contact your hospital administrator.</p></div></div>';return}
    }
    const fn=pages[page]||pages.dashboard;await fn()
  }catch(e){
    if(!token)return renderLogin();
    if(e.message==='MODULE_DISABLED'||e.message==='MODULE_DEPENDENCY_DISABLED'){
      me=await api('/api/me').catch(()=>me);page=firstAccessiblePage();toast('That hospital module has been disabled');if(page)return pages[page]();return
    }
    shell(header('Error','The requested screen could not load')+`<div class="error">${esc(e.message)}</div>`)
  }
}

const pages={};
pages.dashboard=async()=>{let d;try{d=await api('/api/dashboard/role')}catch(e){d=null}if(!d){try{const old=await api('/api/dashboard');d={alerts:[],metrics:[['Patients',old.patients,'PT'],['Appointments today',old.appointments_today,'AP'],['Open encounters',old.open_encounters,'OP'],['Admitted',old.admitted,'IP']].map(([l,v,k])=>({'label':l,'value':String(v),'kind':k})),actions:[],feed:[]}}catch(e2){d={alerts:[],metrics:[],actions:[],feed:[]}}}const alerts=d.alerts||[];const metrics=d.metrics||[];const actions=d.actions||[];const feed=d.feed||[];const alertHtml=alerts.length?`<div class="alertStack">${alerts.map(a=>`<div class="banner banner-${a.level==='danger'?'danger':'warn'}"><div class="bannerTitle"><b>${esc(a.title)}</b><span>${esc(a.detail)}</span></div></div>`).join('')}</div>`:'';const metricHtml=metrics.length?`<div class="statsGrid">${metrics.map(m=>`<div class="stat"><div class="statIcon">${esc(m.kind||'·')}</div><div><b>${esc(m.value)}</b><span>${esc(m.label)}${m.sub?` · ${esc(m.sub)}`:''}</span></div></div>`).join('')}</div>`:'';const actionHtml=actions.length?`<div class="sectionTitle"><h3>Needs action</h3></div><div class="actionGrid">${actions.map(a=>`<div class="panel"><div class="sectionHead"><h3>${esc(a.title)}</h3><span class="badge badge-pending">${a.count}</span></div><div class="actionList">${a.items.map(it=>`<button class="actionRow" data-gopage="${a.page}"><div><b>${esc(it.label)}</b><span>${esc(it.sub)}</span></div><span class="linkBtn">Open ›</span></button>`).join('')||'<div class="empty">All caught up</div>'}</div></div>`).join('')}</div>`:'';const feedHtml=`<div class="panel"><div class="sectionHead"><h3>Activity</h3><span class="muted">recent</span></div><div class="list">${feed.map(f=>`<div class="miniRow"><span>${esc(f.text)}</span><span class="muted">${new Date(f.at).toLocaleString()}</span></div>`).join('')||'<div class="empty">No recent activity</div>'}</div></div>`;shell(header('Hospital overview',`${me.role} · Live operating picture`)+alertHtml+metricHtml+actionHtml+`<div style="margin-top:16px">${feedHtml}</div>`);document.querySelectorAll('[data-gopage]').forEach(b=>b.onclick=()=>{page=b.dataset.gopage;render()})};

pages.patients=async()=>{const rows=await api('/api/patients');shell(header('Patients','Registration, demographics and longitudinal history',can('patients','CREATE')?btn('+ New patient','newPatient'):'')+`<div class="toolbar"><input id="patientSearch" placeholder="Search patient, phone or number"></div><div id="patientsTable">${patientsTable(rows)}</div>`);if(document.getElementById('newPatient'))document.getElementById('newPatient').onclick=()=>patientForm();document.getElementById('patientSearch').oninput=()=>{const q=document.getElementById('patientSearch').value.toLowerCase();document.getElementById('patientsTable').innerHTML=patientsTable(rows.filter(p=>`${p.patient_no} ${p.first_name} ${p.last_name} ${p.phone||''} ${p.nida||''}`.toLowerCase().includes(q)));bindPatientOpen()};bindPatientOpen()};
function patientsTable(rows){return table(['No.','Name','Sex','Phone','Category','Insurance','Blood',''],rows.map(p=>`<tr><td><b>${esc(p.patient_no)}</b></td><td>${esc(p.first_name)} ${esc(p.last_name)}</td><td>${esc(p.sex)}</td><td>${esc(p.phone||'—')}</td><td>${esc(p.patient_category||'—')}</td><td>${esc(p.insurance_type||'—')}</td><td>${esc(p.blood_group||'—')}</td><td>${can('medical_records','VIEW')?`<button class="linkBtn" data-patient="${p.id}">Open ›</button>`:'—'}</td></tr>`))}
async function openPatient(id){const d=await api('/api/patients/'+id);modal(`${esc(d.patient.patient_no)} — ${esc(d.patient.first_name)} ${esc(d.patient.last_name)}`,`<div class="detailGrid"><div class="panel soft"><h3>Patient information</h3><p><b>Phone:</b> ${esc(d.patient.phone||'—')}</p><p><b>NIDA:</b> ${esc(d.patient.nida||'—')}</p><p><b>Category:</b> ${esc(d.patient.patient_category||'—')}</p><p><b>Exemption:</b> ${esc(d.patient.exemption_reason||'—')}</p><p><b>Insurance:</b> ${esc(d.patient.insurance_type||'—')}</p><p><b>Referred from:</b> ${esc(d.patient.referring_facility||'—')}</p><p><b>CTC:</b> ${esc(d.patient.ctc_number||'—')}</p><p><b>Gravida/Para:</b> ${esc(d.patient.gravida_para||'—')}</p><p><b>EDD:</b> ${esc(d.patient.edd||'—')}</p><p><b>Address:</b> ${esc(d.patient.address||'—')}</p><p><b>Blood:</b> ${esc(d.patient.blood_group||'—')}</p><p><b>Allergies:</b> ${esc(d.patient.allergies||'—')}</p><p><b>Next of kin:</b> ${esc(d.patient.next_of_kin||'—')}</p></div><div class="panel soft"><h3>Encounters</h3>${d.encounters.map(x=>`<div class="miniRow"><span>#${x.id} ${esc(x.encounter_type)}</span>${badge(x.status)}</div>`).join('')||'<div class="empty">None</div>'}</div><div class="panel soft"><h3>Appointments</h3>${d.appointments.map(x=>`<div class="miniRow"><span>${new Date(x.scheduled_at).toLocaleDateString()} ${esc(x.department)}</span>${badge(x.status)}</div>`).join('')||'<div class="empty">None</div>'}</div><div class="panel soft"><h3>Invoices</h3>${d.invoices.map(x=>`<div class="miniRow"><span>${money(x.amount)}</span>${badge(x.status)}</div>`).join('')||'<div class="empty">None</div>'}</div></div>`)}
function bindPatientOpen(){document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>openPatient(b.dataset.patient))}
const OTHER='__other__';
function addrOpts(items){return (items||[]).map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}
function addrField(name,label){return field(label,`<div class="addrSel"><select name="${name}"><option value="">— Chagua ${label} —</option><option value="${OTHER}">Nyingine / Other — andika</option></select><input name="${name}_other" type="text" placeholder="Andika ${label}" autocomplete="off" style="display:none"></div>`)}
function setAddr(root,name,label,items){const s=root.querySelector(`select[name="${name}"]`);s.innerHTML=`<option value="">— Chagua ${label} —</option>${addrOpts(items)}<option value="${OTHER}">Nyingine / Other — andika</option>`;root.querySelector(`input[name="${name}_other"]`).style.display='none';s.disabled=false;s.value=''}
function bindAddrCascade(m){
  const r=m.querySelector('select[name=region]'),d=m.querySelector('select[name=district]'),w=m.querySelector('select[name=ward]'),s=m.querySelector('select[name=street]');
  const other=sel=>m.querySelector(`input[name="${sel.name}_other"]`).style.display=sel.value===OTHER?'block':'none';
  setAddr(m,'region','Mkoa',Object.keys(TZ_ADMIN));
  setAddr(m,'district','Wilaya',[]);
  setAddr(m,'ward','Kata',[]);
  setAddr(m,'street','Mtaa / Kijiji',[]);
  r.onchange=()=>{other(r);setAddr(m,'district','Wilaya',Object.keys(TZ_ADMIN[r.value]||{}));setAddr(m,'ward','Kata',[]);setAddr(m,'street','Mtaa / Kijiji',[])};
  d.onchange=()=>{other(d);const rr=TZ_ADMIN[r.value]||{};setAddr(m,'ward','Kata',rr[d.value]||[]);setAddr(m,'street','Mtaa / Kijiji',[])};
  w.onchange=()=>{other(w);setAddr(m,'street','Mtaa / Kijiji',TZ_STREETS[w.value]||[])};
  s.onchange=()=>other(s);
}
function patientForm(){
  const m=modal('Register patient · Usajili wa mgonjwa',`<form id="pf" class="formGrid">
<div class="span2 sectionTitle"><h3>1. Taarifa binafsi · Personal details</h3></div>
${field('First name','<input name="first_name" required>')}${field('Last name','<input name="last_name" required>')}
${field('Sex / Jinsia','<select name="sex"><option>Female</option><option>Male</option><option>Other</option><option>Unknown</option></select>')}
${field('Date of birth · Tarehe ya kuzaliwa','<input name="date_of_birth" type="date"><span class="muted" id="ageHint">Umri utahesabiwa kiotomatiki</span>')}
<div class="span2 sectionTitle"><h3>2. Mawasiliano na anwani · Contact & address</h3></div>
${field('Phone · Namba ya simu','<input name="phone" placeholder="e.g. +255 700 000 000">')}
${field('NIDA · Namba ya kitambulisho','<input name="nida" placeholder="e.g. 19800101123456789012" maxlength="20">')}
${addrField('region','Mkoa')}${addrField('district','Wilaya')}
${addrField('ward','Kata')}${addrField('street','Mtaa / Kijiji')}
<div class="span2 sectionTitle"><h3>3. Bima, kategoria na afya · Insurance, category & health</h3></div>
${field('Aina ya Bima · Insurance type','<select name="insurance_type"><option value="">— Chagua aina ya bima —</option><option>NHIF</option><option>CHF</option><option>iCHF</option><option>Private insurance</option><option>Cash / Malipo ya moja kwa moja</option></select>')}
${field('Kategoria ya Mgonjwa · Patient Category','<select name="patient_category" required><option value="">— Chagua Kategoria —</option><option value="COST_SHARING">Cost Sharing · Malipo ya moja kwa moja</option><option value="NHIF_UHI">NHIF / UHI · Bima ya Afya kwa Wote</option><option value="CHF_LEGACY">CHF · Bima ya jamii (mpito)</option><option value="EXEMPTED">EXEMPTED · Msamaha (mtoto &lt;5, mjamzito, mzee 60+, ugonjwa sugu)</option><option value="WAIVER">WAIVER · Msamaha wa muda (maskini waliothibitishwa)</option></select>')}
<span id="exemptionWrap" style="display:none">${field('Sababu ya Msamaha · Exemption reason','<input name="exemption_reason" placeholder="e.g. Mtoto chini ya 5 / Mjamzito / Mzee 60+ / Ugonjwa sugu" autocomplete="off">')}</span>
${field('Blood group · Kikundi cha damu','<input name="blood_group" placeholder="e.g. O+">')}
${field('Next of kin · Jina la mlezi','<input name="next_of_kin">')}
${field('Allergies · Mzio','<textarea name="allergies"></textarea>')}
<div class="span2 sectionTitle"><h3>4. Ziara, rufaa na huduma maalum · Referral & special care</h3></div>
${field('Kituo kilichotuma · Referring facility','<input name="referring_facility" placeholder="Jina la zahanati / kituo">')}
${field('Namba ya CTC (kama ipo)','<input name="ctc_number" placeholder="e.g. CTC-DSM-012345" autocomplete="off">')}
${field('Gravida/Para (ANC)','<input name="gravida_para" placeholder="e.g. G2P1">')}
${field('EDD · Tarehe inayotarajiwa kujifungua','<input name="edd" type="date">')}
<div class="modalActions span2">${btn('Register · Sajili','savePatient')}</div>
</form>`);
  const dob=m.querySelector('input[name=date_of_birth]'),ageHint=m.querySelector('#ageHint');
  dob.oninput=()=>{const v=dob.value;if(!v){ageHint.textContent='Umri utahesabiwa kiotomatiki';return}const b=new Date(v),n=new Date();let a=n.getFullYear()-b.getFullYear();const md=n.getMonth()-b.getMonth();if(md<0||(md===0&&n.getDate()<b.getDate()))a--;ageHint.textContent=isNaN(a)?'Tarehe si sahihi':`Umri: ${a} miaka`};
  bindAddrCascade(m);
  const cat=m.querySelector('select[name=patient_category]'),ew=m.querySelector('#exemptionWrap');
  cat.onchange=()=>{ew.style.display=cat.value==='EXEMPTED'?'block':'none'};
  m.querySelector('#pf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));
    ['region','district','ward','street'].forEach(k=>{if(o[k]===OTHER)o[k]=(o[k+'_other']||'').trim()||null;else if(!o[k])o[k]=null;delete o[k+'_other']});
    ['sex','phone','nida','blood_group','next_of_kin','allergies','insurance_type','patient_category','exemption_reason','referring_facility','ctc_number','gravida_para','edd','date_of_birth'].forEach(k=>{if(o[k]==='')o[k]=null});
    const parts=[o.street,o.ward,o.district,o.region].filter(Boolean);if(parts.length)o.address=parts.join(', ');
    await api('/api/patients',{method:'POST',body:JSON.stringify(o)});patientRowsCache=null;m.remove();toast('Mgonjwa amesajiliwa · Patient registered');pages.patients()};
}


pages.reception=async()=>{const rows=await api('/api/reception/queue');shell(header('Reception','Patient arrival and front-desk queue')+table(['Patient','Number','Schedule','Department','Clinician','Status',''],rows.map(x=>`<tr><td>${esc(x.patient_name)}</td><td>${esc(x.patient_no||'—')}</td><td>${new Date(x.scheduled_at).toLocaleString()}</td><td>${esc(x.department)}</td><td>${esc(x.clinician||'—')}</td><td>${badge(x.status)}</td><td>${can('reception','EDIT')&&!['ARRIVED','COMPLETED','CANCELLED','NO_SHOW'].includes(x.status)?`<button class="linkBtn" data-checkin="${x.id}">Check in</button>`:''}</td></tr>`)));document.querySelectorAll('[data-checkin]').forEach(b=>b.onclick=async()=>{await api('/api/reception/check-in/'+b.dataset.checkin,{method:'POST'});toast('Patient checked in');pages.reception()})};

pages.appointments=async()=>{const [rows,patients]=await Promise.all([api('/api/appointments'),api('/api/patients')]);const names=Object.fromEntries(patients.map(p=>[p.id,`${p.first_name} ${p.last_name}`]));shell(header('Appointments','Book visits and manage patient arrival',can('appointments','CREATE')?btn('+ Book','newAppointment'):'')+table(['Patient','Schedule','Department','Clinician','Status','Update'],rows.map(x=>`<tr><td>${esc(names[x.patient_id]||'#'+x.patient_id)}</td><td>${new Date(x.scheduled_at).toLocaleString()}</td><td>${esc(x.department)}</td><td>${esc(x.clinician||'—')}</td><td>${badge(x.status)}</td><td><select data-appt="${x.id}"><option ${x.status==='BOOKED'?'selected':''}>BOOKED</option><option ${x.status==='ARRIVED'?'selected':''}>ARRIVED</option><option ${x.status==='COMPLETED'?'selected':''}>COMPLETED</option><option ${x.status==='CANCELLED'?'selected':''}>CANCELLED</option><option ${x.status==='NO_SHOW'?'selected':''}>NO_SHOW</option></select></td></tr>`)));document.querySelectorAll('[data-appt]').forEach(s=>s.onchange=async()=>{await api(`/api/appointments/${s.dataset.appt}/status`,{method:'PATCH',body:JSON.stringify({status:s.value})});toast('Appointment updated');pages.appointments()});if(document.getElementById('newAppointment'))document.getElementById('newAppointment').onclick=()=>appointmentForm(patients)};
function appointmentForm(patients){const m=modal('Book appointment',`<form id="af" class="formGrid">${field('Patient',`<select name="patient_id" required>${patientOptions(patients)}</select>`)}${field('Date & time','<input name="scheduled_at" type="datetime-local" required>')}${field('Department','<input name="department" value="OPD" required>')}${field('Clinician','<input name="clinician">')}${field('Reason','<textarea name="reason"></textarea>')}<div class="modalActions span2">${btn('Save appointment','saveAppt')}</div></form>`);m.querySelector('#af').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.patient_id=Number(o.patient_id);o.scheduled_at=new Date(o.scheduled_at).toISOString();await api('/api/appointments',{method:'POST',body:JSON.stringify(o)});m.remove();toast('Appointment booked');pages.appointments()}}

pages.encounters=async()=>{const [rows,patients]=await Promise.all([api('/api/encounters'),api('/api/patients')]);const names=Object.fromEntries(patients.map(p=>[p.id,`${p.first_name} ${p.last_name}`]));shell(header('OPD & Consultation','Triage, diagnosis, investigations and treatment in one workflow',can('opd','CREATE')?btn('+ Start encounter','newEncounter'):'')+`<div class="cardGrid">${rows.map(x=>`<button class="encCard" data-enc="${x.id}"><div class="encTop"><div><span class="eyebrow">Encounter #${x.id}</span><h3>${esc(names[x.patient_id]||'#'+x.patient_id)}</h3></div>${badge(x.status)}</div><p>${esc(x.chief_complaint||'No chief complaint')}</p><div class="diagnosis"><b>Diagnosis</b><span>${esc(x.diagnosis||'Awaiting consultation')}</span></div></button>`).join('')||'<div class="empty">No encounters</div>'}</div>`);document.querySelectorAll('[data-enc]').forEach(b=>b.onclick=()=>encounterWorkspace(b.dataset.enc));if(document.getElementById('newEncounter'))document.getElementById('newEncounter').onclick=()=>encounterCreate(patients)};
function encounterCreate(patients){const m=modal('Start encounter',`<form id="ef" class="formGrid">${field('Patient',`<select name="patient_id" required>${patientOptions(patients)}</select>`)}${field('Type','<select name="encounter_type"><option>OPD</option><option>FOLLOW_UP</option><option>EMERGENCY</option></select>')}${field('Chief complaint','<textarea name="chief_complaint" required></textarea>')}<div class="modalActions span2">${btn('Open encounter','saveEnc')}</div></form>`);m.querySelector('#ef').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.patient_id=Number(o.patient_id);await api('/api/encounters',{method:'POST',body:JSON.stringify(o)});m.remove();toast('Encounter opened');pages.encounters()}}
async function encounterWorkspace(id){const [d,inventory]=await Promise.all([api('/api/encounters/'+id),api('/api/inventory')]);const m=modal(`Encounter #${id} — ${esc(d.patient.first_name)} ${esc(d.patient.last_name)}`,`<div class="detailGrid"><div class="panel soft"><h3>Triage / vitals</h3><form id="vf">${field('Temperature °C','<input name="temperature_c" type="number" step="0.1">')}${field('Pulse','<input name="pulse" type="number">')}${field('Systolic','<input name="systolic" type="number">')}${field('Diastolic','<input name="diastolic" type="number">')}${field('SpO₂','<input name="spo2" type="number">')}${btn('Save vitals','saveVitals')}</form>${d.vitals.map(v=>`<div class="miniRow"><span>${new Date(v.created_at).toLocaleString()}</span><span>${v.temperature_c??'—'}°C · ${v.pulse??'—'} bpm · ${v.systolic??'—'}/${v.diastolic??'—'}</span></div>`).join('')}</div><div class="panel soft"><h3>Consultation</h3><form id="cf">${field('Clinical notes',`<textarea name="clinical_notes" required>${esc(d.encounter.clinical_notes||'')}</textarea>`)}${field('Diagnosis',`<textarea name="diagnosis" required>${esc(d.encounter.diagnosis||'')}</textarea>`)}${field('Status',`<select name="status"><option ${d.encounter.status==='OPEN'?'selected':''}>OPEN</option><option ${d.encounter.status==='COMPLETED'?'selected':''}>COMPLETED</option><option ${d.encounter.status==='REFERRED'?'selected':''}>REFERRED</option></select>`)}${btn('Save consultation','saveConsult')}</form></div><div class="panel soft"><h3>Laboratory</h3><form id="lf" class="inlineForm"><input name="test_name" placeholder="Test name" required>${btn('Order','saveLab')}</form>${d.labs.map(x=>`<div class="miniRow"><span><b>${esc(x.test_name)}</b><small>${esc(x.result||'No result')}</small></span>${badge(x.status)}</div>`).join('')}</div><div class="panel soft"><h3>Prescriptions</h3><form id="rf">${field('Inventory medicine',`<select name="inventory_item_id"><option value="">Manual medicine</option>${inventory.filter(i=>i.category.toLowerCase().includes('medicine')).map(i=>`<option value="${i.id}" data-name="${esc(i.name)}">${esc(i.name)} (${i.quantity})</option>`).join('')}</select>`)}${field('Medicine','<input name="medicine" required>')}${field('Dose','<input name="dose" required>')}${field('Frequency','<input name="frequency" required>')}${field('Duration','<input name="duration" required>')}${field('Quantity','<input name="quantity" type="number" min="1" value="1" required>')}${btn('Add prescription','saveRx')}</form>${d.prescriptions.map(x=>`<div class="miniRow"><span><b>${esc(x.medicine)}</b><small>${esc(x.dose)} · ${esc(x.frequency)} · ${esc(x.duration)} · Qty ${x.quantity}</small></span>${badge(x.status)}</div>`).join('')}</div></div>`);
  const vf=m.querySelector('#vf');vf.onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));for(const k in o)o[k]=o[k]===''?null:Number(o[k]);o.encounter_id=Number(id);await api('/api/vitals',{method:'POST',body:JSON.stringify(o)});m.remove();encounterWorkspace(id)};
  m.querySelector('#cf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));await api(`/api/encounters/${id}/consultation`,{method:'PATCH',body:JSON.stringify(o)});toast('Consultation saved');m.remove();pages.encounters()};
  m.querySelector('#lf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.encounter_id=Number(id);await api('/api/lab-orders',{method:'POST',body:JSON.stringify(o)});m.remove();encounterWorkspace(id)};
  const sel=m.querySelector('[name=inventory_item_id]');sel.onchange=()=>{const op=sel.options[sel.selectedIndex];if(op.dataset.name)m.querySelector('[name=medicine]').value=op.dataset.name};
  m.querySelector('#rf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.encounter_id=Number(id);o.inventory_item_id=o.inventory_item_id?Number(o.inventory_item_id):null;o.quantity=Number(o.quantity);await api('/api/prescriptions',{method:'POST',body:JSON.stringify(o)});m.remove();encounterWorkspace(id)};
}

pages.laboratory=async()=>{const rows=await api('/api/lab-orders');const pending=rows.filter(x=>x.status==='ORDERED'||x.status==='RESULTED');const cells=x=>{const a=[];if(can('laboratory','EDIT')&&x.status!=='APPROVED')a.push(`<button class="linkBtn" data-lab="${x.id}">Enter result</button>`);if(can('laboratory','VERIFY')&&x.status==='RESULTED')a.push(`<button class="linkBtn" data-verify="${x.id}">Verify</button>`);if(can('laboratory','APPROVE')&&x.verified&&x.status!=='APPROVED')a.push(`<button class="linkBtn" data-approve="${x.id}">Approve</button>`);if(can('laboratory','PRINT'))a.push(`<button class="linkBtn" data-labprint="${x.id}">Print</button>`);return a.join(' ')||'—'};shell(header('Laboratory','Receive orders, enter results and verify them',can('laboratory','EXPORT')?btn('Export CSV','labExport'):'')+(pending.length?`<div class="banner banner-warn"><div class="bannerTitle"><b>Pending verification</b><span>${pending.length} order(s) awaiting verification or approval</span></div></div>`:'')+table(['Order','Encounter','Test','Result','Status','Actions'],rows.map(x=>`<tr><td>#${x.id}</td><td>#${x.encounter_id}</td><td>${esc(x.test_name)}</td><td>${esc(x.result||'—')}</td><td>${badge(x.status)}</td><td>${cells(x)}</td></tr>`)));if(document.getElementById('labExport'))document.getElementById('labExport').onclick=()=>downloadTokenCSV('/api/laboratory/export.csv','laboratory-results.csv');document.querySelectorAll('[data-verify]').forEach(b=>b.onclick=async()=>{await api(`/api/lab-orders/${b.dataset.verify}/verify`,{method:'PATCH'});toast('Result verified');pages.laboratory()});document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{await api(`/api/lab-orders/${b.dataset.approve}/approve`,{method:'POST'});toast('Result approved');pages.laboratory()});document.querySelectorAll('[data-labprint]').forEach(b=>b.onclick=()=>openTokenHTML(`/api/lab-orders/${b.dataset.labprint}/print`));document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>labResult(rows.find(x=>x.id===Number(b.dataset.lab))))};
function labResult(x){const m=modal(`Lab result #${x.id}`,`<form id="lrf">${field(x.test_name,`<textarea name="result" required>${esc(x.result||'')}</textarea>`)}<label class="check"><input name="verified" type="checkbox" ${x.verified?'checked':''}> Verify result now</label><div class="modalActions">${btn('Save result','saveLR')}</div></form>`);m.querySelector('#lrf').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);await api(`/api/lab-orders/${x.id}/result`,{method:'PATCH',body:JSON.stringify({result:fd.get('result'),verified:fd.has('verified')})});m.remove();toast('Lab result saved');pages.laboratory()}}

pages.pharmacy=async()=>{const [rows,inv]=await Promise.all([api('/api/prescriptions'),can('inventory','VIEW')?api('/api/inventory'):Promise.resolve([])]);const low=inv.filter(i=>i.quantity<=i.reorder_level);const banner=low.length?`<div class="banner banner-danger"><div class="bannerTitle"><b>Low stock alert</b><span>${low.length} item(s) at or below reorder level</span></div><div class="bannerList">${low.map(i=>`<span>${esc(i.name)} · ${i.quantity} left (reorder ${i.reorder_level})</span>`).join('')}</div></div>`:'';shell(header('Pharmacy','Dispense prescriptions against live medicine stock')+banner+table(['Rx','Encounter','Medicine','Directions','Qty','Status',''],rows.map(x=>`<tr><td>#${x.id}</td><td>#${x.encounter_id}</td><td>${esc(x.medicine)}</td><td>${esc(x.dose)}, ${esc(x.frequency)}, ${esc(x.duration)}</td><td>${x.quantity}</td><td>${badge(x.status)}</td><td>${x.status==='DISPENSED'?'':`<button class="linkBtn" data-dispense="${x.id}">Dispense</button>`}</td></tr>`)));document.querySelectorAll('[data-dispense]').forEach(b=>b.onclick=async()=>{try{await api(`/api/prescriptions/${b.dataset.dispense}/dispense`,{method:'PATCH'});toast('Medicine dispensed and stock updated');pages.pharmacy()}catch(e){toast(e.message)}})};

pages.billing=async()=>{const [rows,patients]=await Promise.all([api('/api/invoices'),api('/api/patients')]);const names=Object.fromEntries(patients.map(p=>[p.id,`${p.first_name} ${p.last_name}`]));shell(header('Billing & Payments','Invoices, balances and payment collection',can('billing','CREATE')?btn('+ Invoice','newInvoice'):'')+table(['Invoice','Patient','Description','Total','Paid','Balance','Status','Actions'],rows.map(x=>`<tr><td>INV-${String(x.id).padStart(5,'0')}</td><td>${esc(names[x.patient_id]||'#'+x.patient_id)}</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td><td>${money(x.paid_amount)}</td><td>${money(x.amount-x.paid_amount)}</td><td>${badge(x.status)}</td><td>${can('billing','PRINT')?`<button class="linkBtn" data-printinv="${x.id}">Receipt</button>`:''}${x.status==='PAID'?'':` <button class="linkBtn" data-pay="${x.id}">Collect</button>`}</td></tr>`)));if(document.getElementById('newInvoice'))document.getElementById('newInvoice').onclick=()=>invoiceForm(patients);document.querySelectorAll('[data-printinv]').forEach(b=>b.onclick=()=>openTokenHTML(`/api/invoices/${b.dataset.printinv}/print`));document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>paymentForm(rows.find(x=>x.id===Number(b.dataset.pay))))};
function invoiceForm(patients){const m=modal('Create invoice',`<form id="if" class="formGrid">${field('Patient',`<select name="patient_id" required>${patientOptions(patients)}</select>`)}${field('Amount','<input name="amount" type="number" min="1" required>')}${field('Description','<input name="description" value="Clinical services" required>')}<div class="modalActions span2">${btn('Create invoice','saveInv')}</div></form>`);m.querySelector('#if').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.patient_id=Number(o.patient_id);o.amount=Number(o.amount);await api('/api/invoices',{method:'POST',body:JSON.stringify(o)});m.remove();pages.billing()}}
function paymentForm(inv){const due=inv.amount-inv.paid_amount;const m=modal('Collect payment',`<form id="payf" class="formGrid">${field('Amount',`<input name="amount" type="number" min="1" max="${due}" value="${due}" required>`)}${field('Method','<select name="method"><option>CASH</option><option>CARD</option><option>MOBILE_MONEY</option><option>BANK</option><option>INSURANCE</option></select>')}${field('Reference','<input name="reference">')}<div class="modalActions span2">${btn('Record payment','savePay')}</div></form>`);m.querySelector('#payf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.amount=Number(o.amount);await api(`/api/invoices/${inv.id}/payments`,{method:'POST',body:JSON.stringify(o)});m.remove();toast('Payment recorded');pages.billing()}}

pages.inventory=async()=>{const rows=await api('/api/inventory');shell(header('Inventory & Stock','Stock quantities, pricing and movement control',can('inventory','CREATE')?btn('+ Add item','newItem'):'')+table(['SKU','Item','Category','Quantity','Reorder','Unit price',''],rows.map(x=>`<tr class="${x.quantity<=x.reorder_level?'lowStock':''}"><td><b>${esc(x.sku)}</b></td><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${x.quantity}</td><td>${x.reorder_level}</td><td>${money(x.unit_price)}</td><td><button class="linkBtn" data-adjust="${x.id}">Adjust</button></td></tr>`)));if(document.getElementById('newItem'))document.getElementById('newItem').onclick=()=>inventoryForm();document.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>adjustForm(rows.find(x=>x.id===Number(b.dataset.adjust))))};
function inventoryForm(){const m=modal('Add inventory item',`<form id="itemf" class="formGrid">${field('SKU','<input name="sku" required>')}${field('Name','<input name="name" required>')}${field('Category','<input name="category" value="Medicine" required>')}${field('Opening quantity','<input name="quantity" type="number" min="0" value="0">')}${field('Reorder level','<input name="reorder_level" type="number" min="0" value="10">')}${field('Unit price','<input name="unit_price" type="number" min="0" value="0">')}<div class="modalActions span2">${btn('Save item','saveItem')}</div></form>`);m.querySelector('#itemf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['quantity','reorder_level','unit_price'].forEach(k=>o[k]=Number(o[k]));await api('/api/inventory',{method:'POST',body:JSON.stringify(o)});m.remove();pages.inventory()}}
function adjustForm(item){const m=modal(`Adjust ${esc(item.name)} — current ${item.quantity}`,`<form id="adjf">${field('Quantity change (+ receive, − issue)','<input name="delta" type="number" value="0" required>')}${field('Reason','<input name="reason" value="Stock count adjustment" required>')}<div class="modalActions">${btn('Apply adjustment','saveAdj')}</div></form>`);m.querySelector('#adjf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.delta=Number(o.delta);await api(`/api/inventory/${item.id}/adjust`,{method:'POST',body:JSON.stringify(o)});m.remove();pages.inventory()}}

pages.inpatient=async()=>{const [wards,beds,adms,patients]=await Promise.all([api('/api/wards'),api('/api/beds'),api('/api/admissions'),api('/api/patients')]);const names=Object.fromEntries(patients.map(p=>[p.id,`${p.first_name} ${p.last_name}`]));shell(header('Inpatient & Beds','Wards, bed occupancy, admissions and discharge',`<div class="actions">${btn('+ Ward','newWard')}${btn('+ Bed','newBed')}${btn('Admit patient','newAdmission')}</div>`)+`<div class="statsGrid">${wards.map(w=>`<div class="stat"><div><b>${esc(w.name)}</b><span>${beds.filter(b=>b.ward_id===w.id&&b.status==='AVAILABLE').length}/${beds.filter(b=>b.ward_id===w.id).length} beds available</span></div></div>`).join('')}</div>`+table(['Patient','Ward','Bed','Admitted','Status',''],adms.map(a=>`<tr><td>${esc(names[a.patient_id]||'#'+a.patient_id)}</td><td>${esc(wards.find(w=>w.id===a.ward_id)?.name||a.ward_id)}</td><td>${esc(beds.find(b=>b.id===a.bed_id)?.code||a.bed_id)}</td><td>${new Date(a.admitted_at).toLocaleString()}</td><td>${badge(a.status)}</td><td>${a.status==='ADMITTED'?`<button class="linkBtn" data-discharge="${a.id}">Discharge</button>`:''}</td></tr>`)));document.getElementById('newWard').onclick=()=>wardForm();document.getElementById('newBed').onclick=()=>bedForm(wards);document.getElementById('newAdmission').onclick=()=>admissionForm(patients,wards,beds);document.querySelectorAll('[data-discharge]').forEach(b=>b.onclick=async()=>{await api(`/api/admissions/${b.dataset.discharge}/discharge`,{method:'PATCH'});toast('Patient discharged');pages.inpatient()})};
function wardForm(){const m=modal('Create ward',`<form id="wf">${field('Ward name','<input name="name" required>')}${field('Type','<input name="ward_type" value="GENERAL">')}<div class="modalActions">${btn('Create','saveWard')}</div></form>`);m.querySelector('#wf').onsubmit=async e=>{e.preventDefault();await api('/api/wards',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});m.remove();pages.inpatient()}}
function bedForm(wards){const m=modal('Add bed',`<form id="bf">${field('Ward',`<select name="ward_id" required><option value="">Select ward</option>${wards.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select>`)}${field('Bed code','<input name="code" required>')}<div class="modalActions">${btn('Add bed','saveBed')}</div></form>`);m.querySelector('#bf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.ward_id=Number(o.ward_id);await api('/api/beds',{method:'POST',body:JSON.stringify(o)});m.remove();pages.inpatient()}}
function admissionForm(patients,wards,beds){const m=modal('Admit patient',`<form id="admf" class="formGrid">${field('Patient',`<select name="patient_id" required>${patientOptions(patients)}</select>`)}${field('Ward',`<select id="admWard" name="ward_id" required><option value="">Select ward</option>${wards.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select>`)}${field('Bed','<select id="admBed" name="bed_id" required><option value="">Select available bed</option></select>')}${field('Diagnosis','<textarea name="diagnosis"></textarea>')}<div class="modalActions span2">${btn('Admit','saveAdm')}</div></form>`);const admWardEl=m.querySelector('#admWard'),admBedEl=m.querySelector('#admBed');function fill(){admBedEl.innerHTML='<option value="">Select available bed</option>'+beds.filter(b=>b.status==='AVAILABLE'&&(!admWardEl.value||b.ward_id===Number(admWardEl.value))).map(b=>`<option value="${b.id}">${esc(b.code)}</option>`).join('')}admWardEl.onchange=fill;fill();m.querySelector('#admf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['patient_id','ward_id','bed_id'].forEach(k=>o[k]=Number(o[k]));o.encounter_id=null;await api('/api/admissions',{method:'POST',body:JSON.stringify(o)});m.remove();pages.inpatient()}}

pages.operations=async()=>{const mods=await api('/api/modules');const choices=mods.filter(m=>!m.core&&m.enabled&&!['wards','beds'].includes(m.key)&&can(m.key,'VIEW'));const selected=choices.find(x=>x.key===(sessionStorage.getItem('onehms_op_module')||''))||choices[0];const rows=selected?await api('/api/operations/'+selected.key):[];const mod=selected?.key;const cells=r=>{const a=[`<button class="linkBtn" data-op="${r.id}">Update</button>`];if(mod&&can(mod,'VERIFY')&&!r.verified)a.push(`<button class="linkBtn" data-opverify="${r.id}">Verify</button>`);if(mod&&can(mod,'APPROVE')&&r.verified&&!r.approved)a.push(`<button class="linkBtn" data-opapprove="${r.id}">Approve</button>`);if(mod&&can(mod,'DELETE'))a.push(`<button class="linkBtn" data-opdelete="${r.id}">Delete</button>`);return a.join(' ')};shell(header('Specialist modules','Operational workspace for every enabled configurable service',selected&&can(selected.key,'CREATE')?btn('+ New record','newOp'):'')+`<div class="toolbar"><select id="opSelect"><option value="">Choose enabled module</option>${choices.map(m=>`<option value="${m.key}" ${selected?.key===m.key?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div>`+(selected?table(['ID','Patient','Title','Status','Verified','Approved','Created','Actions'],rows.map(r=>`<tr><td>#${r.id}</td><td>${r.patient_id||'—'}</td><td>${esc(r.title)}</td><td>${badge(r.status)}</td><td>${badge(r.verified?'YES':'NO')}</td><td>${badge(r.approved?'YES':'NO')}</td><td>${new Date(r.created_at).toLocaleString()}</td><td>${cells(r)}</td></tr>`)):'<div class="panel empty">Enable a specialist module in Configuration first.</div>'));document.getElementById('opSelect').onchange=()=>{sessionStorage.setItem('onehms_op_module',document.getElementById('opSelect').value);pages.operations()};if(document.getElementById('newOp'))document.getElementById('newOp').onclick=async()=>operationForm(selected.key,await api('/api/patients'));document.querySelectorAll('[data-op]').forEach(b=>b.onclick=async()=>{const status=prompt('New status',rows.find(r=>r.id===Number(b.dataset.op)).status);if(status){await api(`/api/operations/${selected.key}/${b.dataset.op}`,{method:'PATCH',body:JSON.stringify({status})});pages.operations()}});document.querySelectorAll('[data-opverify]').forEach(b=>b.onclick=async()=>{await api(`/api/operations/${selected.key}/${b.dataset.opverify}/verify`,{method:'POST'});toast('Record verified');pages.operations()});document.querySelectorAll('[data-opapprove]').forEach(b=>b.onclick=async()=>{await api(`/api/operations/${selected.key}/${b.dataset.opapprove}/approve`,{method:'POST'});toast('Record approved');pages.operations()});document.querySelectorAll('[data-opdelete]').forEach(b=>b.onclick=async()=>{if(confirm(`Delete record #${b.dataset.opdelete}? This cannot be undone.`)){await api(`/api/operations/${selected.key}/${b.dataset.opdelete}`,{method:'DELETE'});toast('Record deleted');pages.operations()}})};
function operationForm(mod,patients){const m=modal('Create service record',`<form id="opf" class="formGrid">${field('Patient (optional)',`<select name="patient_id">${patientOptions(patients)}</select>`)}${field('Title','<input name="title" required>')}${field('Status','<input name="status" value="OPEN" required>')}${field('Details / notes','<textarea name="notes"></textarea>')}<div class="modalActions span2">${btn('Create record','saveOp')}</div></form>`);m.querySelector('#opf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));await api('/api/operations/'+mod,{method:'POST',body:JSON.stringify({patient_id:o.patient_id?Number(o.patient_id):null,title:o.title,status:o.status,details:{notes:o.notes}})});m.remove();pages.operations()}}

pages.staff=async()=>{const [users,roles]=await Promise.all([api('/api/users'),api('/api/roles')]);shell(header('Users & Roles','Staff accounts and role-based access control',`<div class="actions">${btn('+ User','newUser')}${btn('+ Role','newRole')}</div>`)+table(['Name','Email','Role','Status'],users.map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(u.email)}</td><td>${esc(roles.find(r=>r.id===u.role_id)?.name||u.role_id)}</td><td>${badge(u.active?'ACTIVE':'DISABLED')}</td></tr>`))+`<div class="sectionTitle"><h3>Roles</h3></div>`+table(['Role','Configured modules'],roles.map(r=>`<tr><td>${esc(r.name)}</td><td>${Object.keys(r.permissions||{}).length}</td></tr>`)));document.getElementById('newUser').onclick=()=>userForm(roles);document.getElementById('newRole').onclick=()=>roleForm()};
function userForm(roles){const m=modal('Create staff user',`<form id="uf" class="formGrid">${field('Full name','<input name="full_name" required>')}${field('Email','<input name="email" type="email" required>')}${field('Password','<input name="password" value="Demo123!" required>')}${field('Role',`<select name="role_id" required><option value="">Select role</option>${roles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select>`)}<div class="modalActions span2">${btn('Create user','saveUser')}</div></form>`);m.querySelector('#uf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.role_id=Number(o.role_id);await api('/api/users',{method:'POST',body:JSON.stringify(o)});m.remove();pages.staff()}}
function roleForm(){const m=modal('Create role',`<form id="rolef">${field('Role name','<input name="name" required>')}${field('Starter permissions','<select name="preset"><option value="viewer">Read-only core role</option><option value="editor">Core operational editor</option></select>')}<p class="muted">This creates a safe baseline. Full granular role editing remains available through the API.</p><div class="modalActions">${btn('Create role','saveRole')}</div></form>`);m.querySelector('#rolef').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),perms={},base=['patients','appointments','opd','laboratory','billing','inventory','reports'];base.forEach(k=>perms[k]=fd.get('preset')==='editor'?['VIEW','CREATE','EDIT']:['VIEW']);await api('/api/roles',{method:'POST',body:JSON.stringify({name:fd.get('name'),permissions:perms})});m.remove();pages.staff()}}

pages.reports=async()=>{const [r,an]=await Promise.all([api('/api/reports/summary'),api('/api/reports/analytics?days=30')]);const opdC=an.opd_trend?sparkSVG(an.opd_trend.map(x=>x.count),180,34):'';const revC=an.revenue_trend?sparkSVG(an.revenue_trend.map(x=>x.amount),180,34):'';const bedC=an.bed_occupancy?.length?barSVG(an.bed_occupancy.map(b=>b.ward.slice(0,6)),an.bed_occupancy.map(b=>b.occupied),260,110,'var(--danger)'):'';const deptC=an.department_load?.length?barSVG(an.department_load.map(d=>d.module.slice(0,6)),an.department_load.map(d=>d.count),260,110):'';const testC=an.top_tests?.length?barSVG(an.top_tests.map(t=>t.test.slice(0,8)),an.top_tests.map(t=>t.count),260,110,'var(--accent)'):'';const analyticsHtml=(an.opd_trend||an.revenue_trend||an.bed_occupancy||an.department_load)?`<div class="sectionTitle"><h3>Analytics</h3><span class="muted">${an.days||30}-day window</span></div><div class="detailGrid"><div class="panel"><div class="sectionHead"><h3>OPD encounters trend</h3><span class="muted">${an.totals?.opd??''}</span></div>${opdC||'<div class="empty">No data</div>'}</div><div class="panel"><div class="sectionHead"><h3>Revenue trend</h3><span class="muted">${money(an.totals?.revenue)}</span></div>${revC||'<div class="empty">No data</div>'}</div></div><div class="detailGrid"><div class="panel"><div class="sectionHead"><h3>Bed occupancy</h3></div>${bedC||'<div class="empty">No wards</div>'}</div><div class="panel"><div class="sectionHead"><h3>Department load</h3></div>${deptC||'<div class="empty">No data</div>'}</div></div>${testC?`<div class="detailGrid"><div class="panel"><div class="sectionHead"><h3>Top lab tests</h3></div>${testC}</div></div>`:''}`:'';shell(header('Reports','Operational and financial summary',can('reports','EXPORT')?btn('Export CSV','repExport'):'')+`<div class="statsGrid"><div class="stat"><div><b>${r.patients}</b><span>Total patients</span></div></div><div class="stat"><div><b>${r.encounters}</b><span>Total encounters</span></div></div><div class="stat"><div><b>${r.lab_orders}</b><span>Lab orders</span></div></div><div class="stat"><div><b>${money(r.revenue)}</b><span>Payments collected</span></div></div></div><div class="detailGrid"><div class="panel"><div class="sectionHead"><h3>Invoice status</h3></div>${Object.entries(r.billing_status||{}).map(([k,v])=>`<div class="miniRow"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div><div class="panel"><div class="sectionHead"><h3>Lowest stock</h3></div>${(r.low_stock_items||[]).map(x=>`<div class="miniRow"><span>${esc(x.name)}</span><b>${x.quantity}</b></div>`).join('')||'<div class="empty">No low stock items</div>'}</div></div>${analyticsHtml}`);if(document.getElementById('repExport'))document.getElementById('repExport').onclick=()=>downloadTokenCSV('/api/reports/summary/export.csv','reports-summary.csv')};
pages.audit=async()=>{const rows=await api('/api/audit');shell(header('Audit log','Recent clinical and administrative actions')+table(['Time','User','Action','Entity','ID'],rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>#${x.user_id||'system'}</td><td>${esc(x.action)}</td><td>${esc(x.entity)}</td><td>${esc(x.entity_id||'—')}</td></tr>`)))};
pages.modules=async()=>{const rows=await api('/api/modules');const groups=rows.reduce((a,x)=>((a[x.group]??=[]).push(x),a),{});shell(header('Module configuration','Enable hospital services independently from staff permissions')+`<div class="notice">Disabled modules remain blocked even when a role contains permissions for them.</div><div class="moduleGroups">${Object.entries(groups).map(([g,mods])=>`<div class="panel"><div class="groupHead"><h3>${esc(g)}</h3><span>${mods.filter(m=>m.enabled).length}/${mods.length} enabled</span></div>${mods.map(m=>`<div class="moduleRow"><div><b>${esc(m.name)}</b><small>${m.core?'Core module':'Configurable module'}</small></div><button class="switch ${m.enabled?'on':''}" data-module="${m.key}" ${m.core?'disabled':''}><i></i></button></div>`).join('')}</div>`).join('')}</div>`);document.querySelectorAll('[data-module]').forEach(b=>b.onclick=async()=>{await api('/api/modules/'+b.dataset.module,{method:'PATCH',body:JSON.stringify({enabled:!b.classList.contains('on')})});me=await api('/api/me');pages.modules()})};


// Enhanced administrative screens: complete account, role and facility configuration.
function roleTemplateMap(templates){return Object.fromEntries((templates||[]).map(t=>[t.name,t]))}
function groupedRoleOptions(roles,templates,selected=null){
  const meta=roleTemplateMap(templates),groups={};
  roles.forEach(r=>{const g=meta[r.name]?.category||'Custom Roles';(groups[g]??=[]).push(r)});
  return Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([g,items])=>`<optgroup label="${esc(g)}">${items.sort((a,b)=>a.name.localeCompare(b.name)).map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${esc(r.name)}</option>`).join('')}</optgroup>`).join('')
}
pages.staff=async()=>{
  const [users,roles,mods,templates]=await Promise.all([api('/api/users'),api('/api/roles'),api('/api/modules'),api('/api/role-templates')]);
  const meta=roleTemplateMap(templates),builtIn=roles.filter(r=>meta[r.name]).length;
  shell(header('Users & Roles',`${roles.length} roles available · ${builtIn} predefined hospital roles`,
    `<div class="actions">${btn('Install missing defaults','installRoles')}${btn('+ User','newUser')}${btn('+ Custom role','newRole')}</div>`)+
    `<div class="notice">Staff roles are predefined by hospital function and remain fully editable. Disabled hospital modules still override role permissions.</div>`+
    table(['Name','Email','Role','Department','Status',''],users.map(u=>{const r=roles.find(r=>r.id===u.role_id),t=meta[r?.name];return `<tr><td>${esc(u.full_name)}</td><td>${esc(u.email)}</td><td>${esc(r?.name||u.role_id)}</td><td>${t?roleCat(t.category):'<span class="muted">Custom</span>'}</td><td>${badge(u.active?'ACTIVE':'DISABLED')}</td><td><button class="linkBtn" data-useredit="${u.id}">Edit</button></td></tr>`}))+
    `<div class="sectionTitle"><h3>Hospital role catalogue</h3><span class="muted">${templates.length} built-in templates</span></div>`+
    table(['Role','Department','Purpose','Configured modules',''],roles.map(r=>{const t=meta[r.name];return `<tr><td><b>${esc(r.name)}</b>${t?'<br><small>PREDEFINED</small>':''}</td><td>${esc(t?.category||'Custom')}</td><td>${esc(t?.description||'Hospital-defined custom role')}</td><td>${Object.keys(r.permissions||{}).length}</td><td><button class="linkBtn" data-roleedit="${r.id}">Permissions</button>${t?` <button class="linkBtn" data-rolereset="${r.id}">Reset default</button>`:''}</td></tr>`})));
  document.getElementById('newUser').onclick=()=>userForm(roles,templates);document.getElementById('newRole').onclick=()=>roleForm();
  document.getElementById('installRoles').onclick=async()=>{const x=await api('/api/role-templates/install',{method:'POST'});toast(x.installed_count?`${x.installed_count} role templates installed`:'All predefined roles are already installed');pages.staff()};
  document.querySelectorAll('[data-useredit]').forEach(b=>b.onclick=()=>userEditForm(users.find(u=>u.id===Number(b.dataset.useredit)),roles,templates));
  document.querySelectorAll('[data-roleedit]').forEach(b=>b.onclick=()=>rolePermissionsForm(roles.find(r=>r.id===Number(b.dataset.roleedit)),mods,meta[roles.find(r=>r.id===Number(b.dataset.roleedit))?.name]));
  document.querySelectorAll('[data-rolereset]').forEach(b=>b.onclick=async()=>{const r=roles.find(r=>r.id===Number(b.dataset.rolereset));if(confirm(`Reset ${r.name} to its built-in permission template?`)){await api(`/api/roles/${r.id}/reset-template`,{method:'POST'});toast(`${r.name} restored to default permissions`);pages.staff()}});
};
function userForm(roles,templates=[]){const m=modal('Create staff user',`<form id="uf" class="formGrid">${field('Full name','<input name="full_name" required>')}${field('Email','<input name="email" type="email" required>')}${field('Password','<input name="password" value="Demo123!" required>')}${field('Hospital role',`<select name="role_id" required><option value="">Select role</option>${groupedRoleOptions(roles,templates)}</select>`)}<div class="modalActions span2">${btn('Create user','saveUser')}</div></form>`);m.querySelector('#uf').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.role_id=Number(o.role_id);await api('/api/users',{method:'POST',body:JSON.stringify(o)});m.remove();toast('Staff user created');pages.staff()}}
function userEditForm(u,roles,templates=[]){
  const m=modal('Edit staff user',`<form id="uef" class="formGrid">${field('Full name',`<input name="full_name" value="${esc(u.full_name)}" required>`)}${field('Role',`<select name="role_id">${groupedRoleOptions(roles,templates,u.role_id)}</select>`)}${field('New password (optional)','<input name="password" type="password" placeholder="Leave blank to keep current">')}<label class="check"><input name="active" type="checkbox" ${u.active?'checked':''}> Account active</label><div class="modalActions span2">${btn('Save changes','saveUserEdit')}</div></form>`);
  m.querySelector('#uef').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),o={full_name:fd.get('full_name'),role_id:Number(fd.get('role_id')),active:fd.has('active')};if(fd.get('password'))o.password=fd.get('password');await api('/api/users/'+u.id,{method:'PATCH',body:JSON.stringify(o)});m.remove();toast('User updated');pages.staff()};
}
function rolePermissionsForm(role,mods,template=null){
  const actions=['VIEW','CREATE','EDIT','DELETE','APPROVE','VERIFY','PRINT','EXPORT'];
  const cellsFor=mod=>{const has=mod.supported||actions;return actions.map(a=>has.includes(a)?`<td><input type="checkbox" data-perm="${mod.key}:${a}" ${(role.permissions?.[mod.key]||[]).includes(a)||(role.permissions?.[mod.key]||[]).includes('*')?'checked':''}></td>`:`<td class="muted" title="Not available for this module">–</td>`).join('')};
  const body=`<form id="rpf">${template?`<div class="notice"><b>${esc(template.category)}</b> · ${esc(template.description)}</div>`:''}${field('Role name',`<input name="name" value="${esc(role.name)}" required>`)}<div class="panel tableWrap"><table><thead><tr><th>Module</th>${actions.map(a=>`<th>${a}</th>`).join('')}</tr></thead><tbody>${mods.map(mod=>`<tr><td><b>${esc(mod.name)}</b></td>${cellsFor(mod)}</tr>`).join('')}</tbody></table></div><div class="modalActions">${btn('Save permissions','saveRolePerm')}</div></form>`;
  const m=modal('Role permissions',body);m.querySelector('#rpf').onsubmit=async e=>{e.preventDefault();const permissions={};m.querySelectorAll('[data-perm]:checked').forEach(c=>{const [mod,a]=c.dataset.perm.split(':');(permissions[mod]??=[]).push(a)});await api('/api/roles/'+role.id,{method:'PATCH',body:JSON.stringify({name:new FormData(e.target).get('name'),permissions})});m.remove();toast('Role permissions updated');if(role.id===me.role_id)me=await api('/api/me');pages.staff()};
}
pages.modules=async()=>{
  const rows=await api('/api/modules');const groups=rows.reduce((a,x)=>((a[x.group]??=[]).push(x),a),{});
  shell(header('Hospital & Module Configuration','Facility profile, presets and hospital-wide service switches',btn('Edit hospital','editHospital'))+
    `<div class="panel" style="margin-bottom:14px"><div class="detailGrid"><div><span class="eyebrow">Hospital</span><h3>${esc(me.hospital.name)}</h3><p class="muted">${esc(me.hospital.address||'No address')} · ${esc(me.hospital.phone||'No phone')}</p></div><div><span class="eyebrow">Facility type</span><h3>${esc(me.hospital.facility_type)}</h3><p class="muted">Presets can configure optional modules for the selected facility level.</p></div></div></div>`+
    `<div class="notice">⚙ Disabled modules remain blocked even when a role contains permissions for them. Bed Management requires Inpatient / Wards; enabling Beds also enables Wards, while disabling Wards disables Beds.</div><div class="moduleGroups">${Object.entries(groups).map(([g,mods])=>`<div class="panel"><div class="groupHead"><h3>${esc(g)}</h3><span>${mods.filter(m=>m.enabled).length}/${mods.length} enabled</span></div>${mods.map(m=>`<div class="moduleRow"><div><b>${esc(m.name)}</b><small>${m.core?'Core module':m.key==='beds'?'Configurable module · requires Inpatient / Wards':'Configurable module'}</small></div><button class="switch ${m.enabled?'on':''}" data-module="${m.key}" ${m.core?'disabled':''}><i></i></button></div>`).join('')}</div>`).join('')}</div>`);
  document.getElementById('editHospital').onclick=()=>hospitalForm();document.querySelectorAll('[data-module]').forEach(b=>b.onclick=async()=>{await api('/api/modules/'+b.dataset.module,{method:'PATCH',body:JSON.stringify({enabled:!b.classList.contains('on')})});me=await api('/api/me');pages.modules()});
};
function hospitalForm(){
  const h=me.hospital,m=modal('Hospital settings',`<form id="hf" class="formGrid">${field('Hospital name',`<input name="name" value="${esc(h.name)}" required>`)}${field('Facility type',`<select name="facility_type"><option ${h.facility_type==='SMALL'?'selected':''}>SMALL</option><option ${h.facility_type==='DISTRICT'?'selected':''}>DISTRICT</option><option ${h.facility_type==='REFERRAL'?'selected':''}>REFERRAL</option></select>`)}${field('Address',`<input name="address" value="${esc(h.address||'')}">`)}${field('Phone',`<input name="phone" value="${esc(h.phone||'')}">`)}<label class="check span2"><input name="apply_preset" type="checkbox"> Apply the selected facility preset to all optional modules</label><div class="modalActions span2">${btn('Save hospital settings','saveHospital')}</div></form>`);
  m.querySelector('#hf').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);await api('/api/hospital',{method:'PATCH',body:JSON.stringify({name:fd.get('name'),facility_type:fd.get('facility_type'),address:fd.get('address'),phone:fd.get('phone'),apply_preset:fd.has('apply_preset')})});me=await api('/api/me');m.remove();toast('Hospital configuration updated');pages.modules()};
}

render();
