/* Native care-pathway integration.
 * Keeps departmental screens intact and adds the visit-file context where staff
 * naturally work: reception, OPD, billing, lab, pharmacy, wards and specialist services.
 */
(() => {
  if (typeof pages === 'undefined' || typeof api !== 'function') return;
  const cEsc = s => typeof esc === 'function' ? esc(s) : String(s ?? '');
  const cMoney = n => typeof money === 'function' ? money(n) : `TZS ${Number(n||0).toLocaleString()}`;
  const cToast = m => typeof toast === 'function' ? toast(m) : alert(m);
  const cModal = (t,b) => modal(t,b);
  const dt = x => x ? new Date(x).toLocaleString() : '—';
  const stage = s => ({AWAITING_PAYMENT:'Awaiting payment',TRIAGE:'Triage',WAITING_DOCTOR:'Waiting doctor',WITH_DOCTOR:'With doctor',LAB_PENDING:'Investigations pending',LAB_RESULTS_READY:'Ready for doctor review',PHARMACY_PENDING:'Pharmacy billing',PHARMACY_READY:'Pharmacy ready',CLOSING_PENDING_PHARMACY:'Clinical care complete · pharmacy pending',ADMISSION_PENDING:'Admission pending',ADMITTED:'Admitted',DISCHARGE_PENDING:'Discharge pending',CLOSED:'Closed'}[s]||String(s||''));
  const pill = s => `<span class="carePill">${cEsc(stage(s))}</span>`;
  const content = () => document.querySelector('.content');
  const afterHeader = html => {
    const host=content(); if(!host) return null;
    const wrap=document.createElement('div');wrap.className='careNativeMount';wrap.innerHTML=html;
    const h=host.querySelector('.pageHeader'); if(h?.nextSibling) host.insertBefore(wrap,h.nextSibling); else host.prepend(wrap);return wrap;
  };
  const wrapPage=(name,enhance)=>{const old=pages[name];if(!old||old.__careWrapped)return;const fn=async(...args)=>{await old(...args);try{await enhance()}catch(e){console.warn('care-pathway enhancement',name,e)}};fn.__careWrapped=true;pages[name]=fn};

  async function openVisitModal(id){
    const v=await api(`/api/care/visits/${id}`), mods=await api('/api/modules');
    const enabled=mods.filter(m=>m.enabled);
    const clinical=enabled.filter(m=>['radiology','maternity','theatre','icu','emergency','ambulance','dental','physiotherapy','ophthalmology','ent','pediatrics','mental_health','dialysis','oncology','cardiology','specialized_clinics','blood_bank','nutrition'].includes(m.key));
    const orders=(v.service_orders||[]).map(o=>`<div class="careLine"><div><b>${cEsc(o.title)}</b><span>${cEsc(o.module_key)} · ${cEsc(o.status)}${o.result_summary?` · ${cEsc(o.result_summary)}`:''}</span></div>${o.invoice?`<small>${cMoney(o.invoice.balance)} balance</small>`:''}</div>`).join('')||'<div class="empty">No specialist service orders.</div>';
    const surgeries=(v.surgeries||[]).map(s=>`<div class="careLine"><div><b>${cEsc(s.procedure_name)}</b><span>${cEsc(s.status)}${s.theatre_room?` · ${cEsc(s.theatre_room)}`:''}</span></div></div>`).join('')||'<div class="empty">No theatre case.</div>';
    const labs=(v.labs||[]).map(x=>`<div class="careLine"><div><b>${cEsc(x.test_name)}</b><span>${cEsc(x.status)}${x.result?` · ${cEsc(x.result)}`:''}</span></div></div>`).join('')||'<div class="empty">No laboratory orders.</div>';
    const prescriptions=(v.prescriptions||[]).map(x=>`<div class="careLine"><div><b>${cEsc(x.medicine)}</b><span>${cEsc(x.dose)} · ${cEsc(x.frequency)} · ${cEsc(x.status)}</span></div></div>`).join('')||'<div class="empty">No prescriptions.</div>';
    const blocker=(v.close_blockers||[]).length?`<div class="careWarning"><b>Clinical completion blocked</b><span>${(v.close_blockers||[]).map(cEsc).join(' · ')}</span></div>`:'';
    const admin=v.administrative||{};
    const pv=v.patient||{}, latestVital=(v.vitals||[])[0]||null;
    const allergy=String(pv.allergies||'').trim();
    const allergyAlert=allergy&& !/^(none|no known allergies|nka|nil)$/i.test(allergy)?`<div class="careAllergyAlert"><b>⚠ Allergy alert</b><span>${cEsc(allergy)}</span></div>`:'';
    const vitalLine=latestVital?`${latestVital.temperature_c!=null?`Temp ${cEsc(latestVital.temperature_c)}°C · `:''}${latestVital.pulse!=null?`Pulse ${cEsc(latestVital.pulse)} · `:''}${latestVital.systolic!=null&&latestVital.diastolic!=null?`BP ${cEsc(latestVital.systolic)}/${cEsc(latestVital.diastolic)} · `:''}${latestVital.spo2!=null?`SpO₂ ${cEsc(latestVital.spo2)}% · `:''}${latestVital.weight_kg!=null?`Wt ${cEsc(latestVital.weight_kg)}kg`:''}`.replace(/ · $/,''):'Not recorded';
    const recentEvents=(v.events||[]).slice(-8).reverse().map(e=>`<div class="careTimelineItem"><span></span><div><b>${cEsc(String(e.event_type||'').replaceAll('_',' '))}</b><small>${dt(e.created_at)}${e.note?` · ${cEsc(e.note)}`:''}</small></div></div>`).join('')||'<div class="empty">No visit activity recorded yet.</div>';
    const body=`<div class="careVisitHead"><div><span>${cEsc(v.patient_no)} · visit file</span><h2>${cEsc(v.file_no)} · ${cEsc(v.patient_name)}</h2><p>${pill(v.stage)} ${v.room?`Room ${cEsc(v.room)}`:''}</p></div><div class="careVisitMeta"><span>${cEsc(admin.payer_type||'CASH')}</span><b>${cEsc(admin.department||'OPD')}</b></div></div>${allergyAlert}${blocker}
      <div class="careActionBar">
        ${can('triage','CREATE')&&v.stage==='TRIAGE'?'<button class="primary" data-care-triage>Record triage</button>':''}
        ${can('consultation','EDIT')?`<button class="ghost" data-care-consult>Clinical note</button>${enabled.some(m=>m.key==='laboratory')?'<button class="ghost" data-care-lab>Order lab</button>':''}${can('prescriptions','CREATE')?'<button class="ghost" data-care-rx>Prescribe</button>':''}<button class="ghost" data-care-service>Order service</button>${enabled.some(m=>m.key==='theatre')?'<button class="ghost" data-care-surgery>Request surgery</button>':''}<button class="ghost" data-care-referral>Referral / transfer</button>${!v.admission&&v.status==='OPEN'?'<button class="primary" data-care-outcome>Disposition</button>':''}${v.stage==='ADMITTED'?'<button class="primary" data-care-discharge-decision>Discharge decision</button>':''}`:''}
        ${can('reception','EDIT')?'<button class="ghost" data-care-admin>Payer / department</button>':''}
        ${v.stage==='ADMISSION_PENDING'&&can('wards','CREATE')?'<button class="primary" data-care-admit>Assign ward & bed</button>':''}
        ${(v.admission&&can('wards','EDIT'))?'<button class="ghost" data-care-progress>Progress note</button><button class="ghost" data-care-plan>Discharge plan</button><button class="ghost" data-care-med>Medication administration</button><button class="ghost" data-care-transfer>Transfer bed</button>':''}
        ${v.stage==='DISCHARGE_PENDING'&&can('billing','EDIT')?'<button class="ghost" data-care-clearance>Financial clearance</button>':''}
        ${v.stage==='DISCHARGE_PENDING'&&can('wards','EDIT')?'<button class="primary" data-care-complete-discharge>Complete discharge</button>':''}
      </div>
      <div class="careVisitGrid"><section><h3>Clinical episode</h3><dl><dt>Reason</dt><dd>${cEsc(v.reason||v.encounter?.chief_complaint||'—')}</dd><dt>Diagnosis</dt><dd>${cEsc(v.encounter?.diagnosis||'—')}</dd><dt>Latest vitals</dt><dd>${vitalLine}</dd><dt>Blood group</dt><dd>${cEsc(pv.blood_group||'Not recorded')}</dd><dt>Doctor</dt><dd>${cEsc(v.doctor_name||'Unassigned')}</dd><dt>Room</dt><dd>${cEsc(v.room||'—')}</dd></dl></section><section><h3>Administrative</h3><dl><dt>Payer</dt><dd>${cEsc(admin.payer_type||'CASH')} ${admin.payer_name?`· ${cEsc(admin.payer_name)}`:''}</dd><dt>Authorization</dt><dd>${cEsc(admin.authorization_status||'NOT_REQUIRED')}</dd><dt>Department</dt><dd>${cEsc(admin.department||'OPD')}</dd><dt>Referral source</dt><dd>${cEsc(admin.referral_source||'—')}</dd></dl></section></div>
      <div class="careVisitGrid"><section><h3>Laboratory</h3>${labs}</section><section><h3>Prescriptions</h3>${prescriptions}</section></div>
      <div class="careVisitGrid"><section><h3>Department orders</h3>${orders}</section><section><h3>Theatre / procedures</h3>${surgeries}</section></div>
      <div class="panel soft careFinance"><h3>Visit financial position</h3><div class="careFinanceRow"><span>Total ${cMoney(v.financial?.total||0)}</span><span>Paid ${cMoney(v.financial?.paid||0)}</span><b>Balance ${cMoney(v.financial?.balance||0)}</b></div></div>
      <div class="panel soft careTimeline"><h3>Recent episode activity</h3>${recentEvents}</div>
      ${(v.discharge_plan)?`<div class="panel soft careDischarge"><h3>Discharge / follow-up plan</h3><p><b>${cEsc(v.discharge_plan.disposition)}</b> · ${cEsc(v.discharge_plan.final_diagnosis||'Diagnosis not entered')}</p><p>${cEsc(v.discharge_plan.instructions||'')}</p><small>Financial clearance: ${cEsc(v.discharge_plan.financial_clearance)}</small></div>`:''}`;
    const m=cModal(`Care file ${v.file_no}`,body);
    m.querySelector('[data-care-triage]')?.addEventListener('click',()=>triageForm(v,m));
    m.querySelector('[data-care-consult]')?.addEventListener('click',()=>clinicalNote(v,m));
    m.querySelector('[data-care-lab]')?.addEventListener('click',()=>labOrderForm(v,m));
    m.querySelector('[data-care-rx]')?.addEventListener('click',()=>prescriptionForm(v,m));
    m.querySelector('[data-care-service]')?.addEventListener('click',()=>serviceOrder(v,clinical,m));
    m.querySelector('[data-care-surgery]')?.addEventListener('click',()=>surgeryRequest(v,m));
    m.querySelector('[data-care-referral]')?.addEventListener('click',()=>referralForm(v,clinical,m));
    m.querySelector('[data-care-outcome]')?.addEventListener('click',()=>dispositionForm(v,m));
    m.querySelector('[data-care-discharge-decision]')?.addEventListener('click',()=>dischargeDecisionForm(v,m));
    m.querySelector('[data-care-admin]')?.addEventListener('click',()=>adminForm(v,m));
    m.querySelector('[data-care-admit]')?.addEventListener('click',()=>admissionAssign(v,m));
    m.querySelector('[data-care-progress]')?.addEventListener('click',()=>progressForm(v,m));
    m.querySelector('[data-care-plan]')?.addEventListener('click',()=>dischargePlanForm(v,m));
    m.querySelector('[data-care-med]')?.addEventListener('click',()=>medAdminForm(v,m));
    m.querySelector('[data-care-transfer]')?.addEventListener('click',()=>bedTransferForm(v,m));
    m.querySelector('[data-care-clearance]')?.addEventListener('click',()=>financialClearance(v,m));
    m.querySelector('[data-care-complete-discharge]')?.addEventListener('click',()=>completeDischarge(v,m));
  }

  function triageForm(v,parent){const last=v.vitals?.[0]||{};const m=cModal('Triage & vital signs',`<form id="careTriage" class="formGrid">${field('Temperature °C',`<input name="temperature_c" type="number" step="0.1" value="${last.temperature_c||''}">`)}${field('Pulse / min',`<input name="pulse" type="number" value="${last.pulse||''}">`)}${field('BP systolic',`<input name="systolic" type="number" value="${last.systolic||''}">`)}${field('BP diastolic',`<input name="diastolic" type="number" value="${last.diastolic||''}">`)}${field('SpO₂ %',`<input name="spo2" type="number" value="${last.spo2||''}">`)}${field('Weight kg',`<input name="weight_kg" type="number" step="0.1" value="${last.weight_kg||''}">`)}<div class="modalActions span2"><button class="primary">Complete triage</button></div></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));Object.keys(o).forEach(k=>o[k]=o[k]===''?null:Number(o[k]));await api(`/api/journey/visits/${v.id}/triage`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Triage completed');pages.encounters()}}
  function labOrderForm(v,parent){const m=cModal('Order laboratory tests',`<form id="careLabOrder">${field('Tests — one per line','<textarea name="tests" rows="6" required placeholder="Full Blood Count\nMalaria RDT"></textarea>')}<div class="modalActions"><button class="primary">Send to laboratory</button></div></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();const tests=String(new FormData(e.target).get('tests')||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean);await api(`/api/journey/visits/${v.id}/lab-orders`,{method:'POST',body:JSON.stringify({tests})});m.remove();parent.remove();cToast('Laboratory order sent');pages.encounters()}}
  async function prescriptionForm(v,parent){const inv=await api('/api/inventory').catch(()=>[]);const m=cModal('Prescribe treatment',`<form id="careRx" class="formGrid">${field('Source','<select name="source"><option>HOSPITAL</option><option>EXTERNAL</option></select>')}${field('Hospital stock item',`<select name="inventory_item_id"><option value="">Not linked / external</option>${inv.map(x=>`<option value="${x.id}" data-name="${cEsc(x.name)}">${cEsc(x.name)} · ${x.quantity} in stock</option>`).join('')}</select>`)}${field('Medicine','<input name="medicine" required>')}${field('Dose','<input name="dose" required placeholder="500 mg">')}${field('Frequency','<input name="frequency" required placeholder="3 times daily">')}${field('Duration','<input name="duration" required placeholder="5 days">')}${field('Quantity','<input name="quantity" type="number" min="1" value="1" required>')}${field('Instructions','<textarea name="instructions"></textarea>')}<div class="modalActions span2"><button class="primary">Save prescription</button></div></form>`);const sel=m.querySelector('[name=inventory_item_id]');sel.onchange=()=>{const op=sel.options[sel.selectedIndex];if(op?.dataset.name)m.querySelector('[name=medicine]').value=op.dataset.name};m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const source=o.source;delete o.source;o.inventory_item_id=o.inventory_item_id?Number(o.inventory_item_id):null;o.quantity=Number(o.quantity);await api(`/api/journey/visits/${v.id}/prescriptions`,{method:'POST',body:JSON.stringify({source,medicines:[o]})});m.remove();parent.remove();cToast(source==='HOSPITAL'?'Prescription sent to hospital pharmacy':'External prescription documented');openVisitModal(v.id)}}
  function dispositionForm(v,parent){const m=cModal('Clinical disposition',`<form id="careDisposition" class="formGrid">${field('Outcome','<select name="outcome"><option>OUTPATIENT</option><option>ADMIT</option></select>')}${field('Medicine source if outpatient','<select name="pharmacy_choice"><option>NONE</option><option>HOSPITAL</option><option>EXTERNAL</option></select>')}${field('Clinical plan / note','<textarea name="note" rows="5"></textarea>')}<div class="modalActions span2"><button class="primary">Confirm clinical decision</button></div></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.outcome==='ADMIT')o.pharmacy_choice=null;await api(`/api/journey/visits/${v.id}/outcome`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast(o.outcome==='ADMIT'?'Admission requested':'Clinical disposition saved');pages.encounters()}}
  async function admissionAssign(v,parent){const [wards,beds]=await Promise.all([api('/api/wards'),api('/api/beds')]);const avail=beds.filter(b=>b.status==='AVAILABLE');const m=cModal('Assign ward & bed',`<form id="careAdmission" class="formGrid">${field('Ward',`<select name="ward_id" required><option value="">Select ward</option>${wards.map(w=>`<option value="${w.id}">${cEsc(w.name)}</option>`).join('')}</select>`)}${field('Bed',`<select name="bed_id" required><option value="">Select available bed</option>${avail.map(b=>`<option value="${b.id}" data-ward="${b.ward_id}">${cEsc(b.code)}</option>`).join('')}</select>`)}${field('Admission diagnosis',`<textarea name="diagnosis">${cEsc(v.encounter?.diagnosis||'')}</textarea>`)}<div class="modalActions span2"><button class="primary">Admit patient</button></div></form>`);const ws=m.querySelector('[name=ward_id]'),bs=m.querySelector('[name=bed_id]');const filterBeds=()=>{[...bs.options].forEach((o,i)=>{if(i)o.hidden=!!ws.value&&o.dataset.ward!==ws.value});if(bs.selectedOptions[0]?.hidden)bs.value=''};ws.onchange=filterBeds;m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.patient_id=v.patient_id;o.encounter_id=v.encounter_id;o.ward_id=Number(o.ward_id);o.bed_id=Number(o.bed_id);await api(`/api/journey/visits/${v.id}/admit`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Patient admitted');pages.inpatient()}}
  function progressForm(v,parent){const m=cModal('Inpatient progress note',`<form id="careProgress">${field('Type','<select name="note_type"><option>PROGRESS</option><option>NURSING</option><option>DOCTOR</option><option>OBSERVATION</option><option>PROCEDURE</option></select>')}${field('Note','<textarea name="note" rows="6" required></textarea>')}<div class="modalActions"><button class="primary">Add note</button></div></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();await api(`/api/journey/visits/${v.id}/progress`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});m.remove();parent.remove();cToast('Progress note added');openVisitModal(v.id)}}
  function dischargeDecisionForm(v,parent){const m=cModal('Doctor discharge decision',`<form id="careDischargeDecision">${field('Discharge summary / clinical plan','<textarea name="summary" rows="7" required></textarea>')}<div class="notice">The ward will complete physical discharge after the discharge plan, outstanding clinical work and required financial clearance are complete.</div><div class="modalActions"><button class="primary">Approve discharge</button></div></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();await api(`/api/journey/visits/${v.id}/discharge-decision`,{method:'POST',body:JSON.stringify({summary:new FormData(e.target).get('summary')})});m.remove();parent.remove();cToast('Discharge approved by doctor');pages.encounters()}}
  async function financialClearance(v,parent){try{await api(`/api/care/visits/${v.id}/financial-clearance`,{method:'POST',body:JSON.stringify({status:'CLEARED'})});parent.remove();cToast('Financial clearance recorded');pages.billing()}catch(e){cToast(e.message)}}
  async function completeDischarge(v,parent){try{await api(`/api/journey/visits/${v.id}/discharge`,{method:'POST',body:'{}'});parent.remove();cToast('Patient discharged and visit file closed');pages.inpatient()}catch(e){cToast(e.message)}}

  function clinicalNote(v,parent){const e=v.encounter||{};const m=cModal('Clinical note',`<form id="careClinical">${field('Chief complaint',`<textarea name="chief_complaint">${cEsc(e.chief_complaint||v.reason||'')}</textarea>`)}${field('Clinical notes',`<textarea name="clinical_notes" rows="5">${cEsc(e.clinical_notes||'')}</textarea>`)}${field('Diagnosis / assessment',`<textarea name="diagnosis" rows="3">${cEsc(e.diagnosis||'')}</textarea>`)}<div class="modalActions"><button class="primary">Save</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();await api(`/api/journey/visits/${v.id}/consultation`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});m.remove();parent.remove();cToast('Clinical record updated');pages.encounters()}}
  function serviceOrder(v,mods,parent){const m=cModal('Order hospital service',`<form id="careService" class="formGrid">${field('Service',`<select name="module_key" required><option value="">Select service</option>${mods.map(x=>`<option value="${x.key}">${cEsc(x.name)}</option>`).join('')}</select>`)}${field('Priority','<select name="priority"><option>NORMAL</option><option>URGENT</option><option>EMERGENCY</option></select>')}${field('Request / procedure / imaging', '<input name="title" required>')}${field('Estimated charge (optional)','<input name="amount" type="number" min="0" value="0">')}${field('Clinical question / reason','<textarea name="clinical_question" rows="4"></textarea>')}<div class="modalActions span2"><button class="primary">Send order</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.amount=Number(o.amount||0);await api(`/api/care/visits/${v.id}/service-orders`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Order sent to department');openVisitModal(v.id)}}
  function surgeryRequest(v,parent){const m=cModal('Request theatre / surgery',`<form id="careSurgery" class="formGrid">${field('Procedure','<input name="procedure_name" required>')}${field('Urgency','<select name="urgency"><option>ELECTIVE</option><option>URGENT</option><option>EMERGENCY</option></select>')}${field('Estimated charge','<input name="amount" type="number" min="0" value="0">')}${field('Indication / reason','<textarea name="clinical_question" rows="4"></textarea>')}<div class="modalActions span2"><button class="primary">Request theatre</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.amount=Number(o.amount||0);await api(`/api/care/visits/${v.id}/surgery`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Surgical case requested');openVisitModal(v.id)}}
  function referralForm(v,mods,parent){const m=cModal('Referral / transfer',`<form id="careReferral" class="formGrid">${field('Type','<select name="kind"><option>INTERNAL</option><option>EXTERNAL</option><option>TRANSFER</option></select>')}${field('Internal service',`<select name="target_module"><option value="">Not applicable</option>${mods.map(x=>`<option value="${x.key}">${cEsc(x.name)}</option>`).join('')}</select>`)}${field('External facility','<input name="target_facility">')}${field('Reason','<textarea name="reason" required></textarea>')}<div class="modalActions span2"><button class="primary">Create referral</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));if(!o.target_module)o.target_module=null;if(!o.target_facility)o.target_facility=null;await api(`/api/care/visits/${v.id}/referrals`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Referral created');openVisitModal(v.id)}}
  function adminForm(v,parent){const a=v.administrative||{};const m=cModal('Visit administration',`<form id="careAdmin" class="formGrid">${field('Payer','<select name="payer_type"><option>CASH</option><option>INSURANCE</option><option>CORPORATE</option><option>EXEMPT</option></select>')}${field('Payer / insurer name',`<input name="payer_name" value="${cEsc(a.payer_name||'')}">`)}${field('Member / policy number',`<input name="member_no" value="${cEsc(a.member_no||'')}">`)}${field('Authorization','<select name="authorization_status"><option>NOT_REQUIRED</option><option>PENDING</option><option>APPROVED</option><option>DECLINED</option></select>')}${field('Department',`<input name="department" value="${cEsc(a.department||'OPD')}">`)}${field('Referral source',`<input name="referral_source" value="${cEsc(a.referral_source||'')}">`)}<div class="modalActions span2"><button class="primary">Save</button></div></form>`);m.querySelector('[name=payer_type]').value=a.payer_type||'CASH';m.querySelector('[name=authorization_status]').value=a.authorization_status||'NOT_REQUIRED';m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));await api(`/api/care/visits/${v.id}/administrative`,{method:'PATCH',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Visit administration updated');openVisitModal(v.id)}}
  function dischargePlanForm(v,parent){const d=v.discharge_plan||{};const m=cModal('Discharge & follow-up plan',`<form id="carePlan" class="formGrid">${field('Disposition','<select name="disposition"><option>HOME</option><option>TRANSFERRED</option><option>LEFT_AGAINST_ADVICE</option></select>')}${field('Final diagnosis',`<textarea name="final_diagnosis" required>${cEsc(d.final_diagnosis||v.encounter?.diagnosis||'')}</textarea>`)}${field('Condition at discharge',`<textarea name="condition_at_discharge">${cEsc(d.condition_at_discharge||'')}</textarea>`)}${field('Instructions / medicines / warning signs',`<textarea name="instructions" rows="5" required>${cEsc(d.instructions||'')}</textarea>`)}${field('Follow-up date','<input name="follow_up_at" type="datetime-local">')}${field('Follow-up department',`<input name="follow_up_department" value="${cEsc(d.follow_up_department||'OPD')}">`)}<div class="modalActions span2"><button class="primary">Save plan</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.follow_up_at=o.follow_up_at?new Date(o.follow_up_at).toISOString():null;await api(`/api/care/visits/${v.id}/discharge-plan`,{method:'PUT',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Discharge plan saved');openVisitModal(v.id)}}
  function medAdminForm(v,parent){const rxs=v.prescriptions||[];const m=cModal('Medication administration',`<form id="careMAR" class="formGrid">${field('Prescription',`<select name="prescription_id"><option value="">Manual / not linked</option>${rxs.map(x=>`<option value="${x.id}" data-med="${cEsc(x.medicine)}" data-dose="${cEsc(x.dose)}">${cEsc(x.medicine)} · ${cEsc(x.dose)}</option>`).join('')}</select>`)}${field('Medicine','<input name="medicine" required>')}${field('Dose','<input name="dose" required>')}${field('Route','<select name="route"><option>ORAL</option><option>IV</option><option>IM</option><option>SC</option><option>TOPICAL</option><option>OTHER</option></select>')}${field('Status','<select name="status"><option>GIVEN</option><option>HELD</option><option>REFUSED</option><option>OMITTED</option></select>')}${field('Notes','<textarea name="notes"></textarea>')}<div class="modalActions span2"><button class="primary">Record administration</button></div></form>`);const sel=m.querySelector('[name=prescription_id]');sel.onchange=()=>{const op=sel.options[sel.selectedIndex];if(op.dataset.med){m.querySelector('[name=medicine]').value=op.dataset.med;m.querySelector('[name=dose]').value=op.dataset.dose}};m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.prescription_id=o.prescription_id?Number(o.prescription_id):null;await api(`/api/care/visits/${v.id}/medication-administrations`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Medication administration recorded');openVisitModal(v.id)}}
  async function bedTransferForm(v,parent){const [wards,beds]=await Promise.all([api('/api/wards'),api('/api/beds')]),avail=beds.filter(b=>b.status==='AVAILABLE');const m=cModal('Transfer ward / bed',`<form id="careBed" class="formGrid">${field('Ward',`<select name="ward_id" required><option value="">Select</option>${wards.map(w=>`<option value="${w.id}">${cEsc(w.name)}</option>`).join('')}</select>`)}${field('Bed',`<select name="bed_id" required><option value="">Select available bed</option>${avail.map(b=>`<option value="${b.id}">${cEsc(b.code)}</option>`).join('')}</select>`)}${field('Reason','<textarea name="reason"></textarea>')}<div class="modalActions span2"><button class="primary">Transfer patient</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.ward_id=Number(o.ward_id);o.bed_id=Number(o.bed_id);await api(`/api/care/visits/${v.id}/bed-transfer`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();cToast('Bed transfer completed');pages.inpatient()}}

  function visitRows(rows,action='Open file'){return rows.map(v=>`<div class="careQueueRow"><div><b>${cEsc(v.file_no)} · ${cEsc(v.patient_name)}</b><span>${cEsc(v.patient_no)} · ${pill(v.stage)}${v.room?` · Room ${cEsc(v.room)}`:''}</span></div><button class="linkBtn" data-care-visit="${v.id}">${action}</button></div>`).join('')||'<div class="empty">No active visit files in this queue.</div>'}
  function bindVisitButtons(host=document){host.querySelectorAll('[data-care-visit]').forEach(b=>b.onclick=()=>openVisitModal(Number(b.dataset.careVisit)))}

  wrapPage('dashboard',async()=>{
    const r=await api('/api/journey/visits?status=OPEN').catch(()=>[]);const urgent=r.filter(x=>x.priority==='EMERGENCY'||x.priority==='URGENT').length;
    const m=afterHeader(`<div class="careDashboardStrip"><div><span>Active visit files</span><b>${r.length}</b></div><div><span>Urgent / emergency</span><b>${urgent}</b></div><div><span>Admitted</span><b>${r.filter(x=>x.stage==='ADMITTED').length}</b></div><div><span>Awaiting doctor</span><b>${r.filter(x=>['WAITING_DOCTOR','LAB_RESULTS_READY'].includes(x.stage)).length}</b></div></div>`);return m;
  });

  wrapPage('reception',async()=>{
    const rows=await api('/api/journey/visits?status=OPEN');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Visit files</span><h3>Receive patient & open today’s episode</h3><p>One patient number stays permanent; every visit gets its own file until clinical completion/discharge.</p></div>${can('reception','CREATE')?'<button class="primary" id="careOpenVisit">+ Open visit file</button>':''}</div><div class="careQueue">${visitRows(rows.slice(0,10))}</div></div>`);bindVisitButtons(m);m.querySelector('#careOpenVisit')?.addEventListener('click',receptionOpen);
  });
  async function receptionOpen(){const patients=await api('/api/patients');const m=cModal('Open patient visit file',`<form id="careOpen" class="formGrid">${field('Patient',`<select name="patient_id" required>${patientOptions(patients)}</select>`)}${field('Priority','<select name="priority"><option>NORMAL</option><option>URGENT</option><option>EMERGENCY</option></select>')}${field('Payer','<select name="payer_type"><option>CASH</option><option>INSURANCE</option><option>CORPORATE</option><option>EXEMPT</option></select>')}${field('Authorization','<select name="authorization_status"><option>NOT_REQUIRED</option><option>PENDING</option><option>APPROVED</option><option>DECLINED</option></select>')}${field('Insurer / company','<input name="payer_name">')}${field('Member / policy no.','<input name="member_no">')}${field('Department','<input name="department" value="OPD">')}${field('Referral source','<input name="referral_source">')}${field('Reason / presenting complaint','<textarea name="reason" required></textarea>')}<div class="notice span2">Emergency care proceeds to triage without waiting for cash. Approved insurance/corporate care remains invoiced but does not block treatment.</div><div class="modalActions span2"><button class="primary">Open visit file</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.patient_id=Number(o.patient_id);['payer_name','member_no','referral_source'].forEach(k=>{if(!o[k])o[k]=null});const v=await api('/api/journey/visits',{method:'POST',body:JSON.stringify(o)});m.remove();cToast(`Visit ${v.file_no} opened`);pages.reception()}}

  wrapPage('billing',async()=>{const q=await api('/api/journey/billing-queue');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Patient flow billing</span><h3>Charges affecting the current care episode</h3></div></div><div class="careQueue">${q.slice(0,12).map(x=>`<div class="careQueueRow"><div><b>${cEsc(x.file_no)} · ${cEsc(x.patient_name)}</b><span>${cEsc(x.kind)} · ${cMoney(x.invoice.balance)} balance</span></div><button class="linkBtn" data-care-visit="${x.visit_id}">Open file</button></div>`).join('')||'<div class="empty">No visit-flow payments pending.</div>'}</div></div>`);bindVisitButtons(m)});

  wrapPage('encounters',async()=>{
    const mounts=[];
    if(can('triage','CREATE')){const all=await api('/api/journey/visits?status=OPEN');const tq=all.filter(x=>x.stage==='TRIAGE');const t=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Triage queue</span><h3>Patients awaiting vital signs & urgency assessment</h3><p>Emergency and policy-routed patients enter clinical care here.</p></div></div><div class="careQueue">${visitRows(tq,'Triage')}</div></div>`);bindVisitButtons(t);mounts.push(t)}
    if(can('consultation','VIEW')){const n=await api('/api/care/native/doctor');let w={my_shift:null};try{w=await api('/api/journey/workspace')}catch(e){}const shift=w.my_shift;const editable=can('consultation','EDIT');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Doctor queue</span><h3>${editable?(shift?`Room ${cEsc(shift.room_number)} · ${cEsc(shift.availability)}`:'Not currently on a doctor shift'):'Clinical review queue'}</h3><p>Visit files return here after laboratory, imaging and specialist services.</p></div>${editable?`<div class="actions">${shift?`<button class="ghost" id="careAvailability">${shift.availability==='AVAILABLE'?'Mark away':'Mark available'}</button>`:'<button class="primary" id="careStartShift">Start shift</button>'}</div>`:''}</div>${editable?'<div class="careDoctorSearch"><input id="careDoctorSearch" placeholder="Patient number or file number"><button class="ghost" id="careDoctorSearchBtn">Find</button></div><div id="careDoctorResults"></div>':''}<div class="careQueue">${visitRows(n.visits||[])}</div></div>`);bindVisitButtons(m);if(editable){m.querySelector('#careStartShift')?.addEventListener('click',()=>shiftStart());m.querySelector('#careAvailability')?.addEventListener('click',async()=>{await api('/api/journey/doctor/availability',{method:'PATCH',body:JSON.stringify({availability:shift.availability==='AVAILABLE'?'AWAY':'AVAILABLE'})});pages.encounters()});const find=async()=>{const q=m.querySelector('#careDoctorSearch').value.trim();if(!q)return;const rows=await api('/api/journey/visits?q='+encodeURIComponent(q)+'&status=OPEN');m.querySelector('#careDoctorResults').innerHTML=`<div class="careQueue">${visitRows(rows)}</div>`;bindVisitButtons(m)};m.querySelector('#careDoctorSearchBtn').onclick=find;m.querySelector('#careDoctorSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();find()}}}mounts.push(m)}
    return mounts;
  });
  function shiftStart(){const m=cModal('Start doctor shift',`<form id="careShift">${field('Room / consulting room','<input name="room_number" required placeholder="e.g. OPD-03">')}<div class="modalActions"><button class="primary">Start shift</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();await api('/api/journey/doctor/shift/start',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});m.remove();cToast('Doctor shift started');pages.encounters()}}

  wrapPage('laboratory',async()=>{const q=await api('/api/journey/lab-queue');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Visit-file laboratory queue</span><h3>Orders received from clinicians</h3><p>Results stay attached to the same visit file and return to doctor review automatically.</p></div></div><div class="careQueue">${q.slice(0,15).map(x=>`<div class="careQueueRow"><div><b>${cEsc(x.file_no)} · ${cEsc(x.patient_name)}</b><span>${cEsc(x.test_name)} · ${cEsc(x.status)}</span></div><button class="linkBtn" data-care-visit="${x.visit_id}">Open file</button></div>`).join('')||'<div class="empty">No visit-file lab orders.</div>'}</div></div>`);bindVisitButtons(m)});
  wrapPage('pharmacy',async()=>{const q=await api('/api/journey/pharmacy-queue');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Treatment queue</span><h3>Hospital-pharmacy patients</h3><p>Only prescriptions the patient chose to obtain from this hospital appear here.</p></div></div><div class="careQueue">${visitRows(q.slice(0,15))}</div></div>`);bindVisitButtons(m)});

  wrapPage('inpatient',async()=>{const n=await api('/api/care/native/inpatient');const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Inpatient episode</span><h3>Admission, ward care, transfers and discharge</h3><p>The original visit file remains open throughout the admission.</p></div></div><div class="careQueue">${visitRows(n.visits||[])}</div></div>`);bindVisitButtons(m)});

  wrapPage('operations',async()=>{const sel=document.querySelector('#opSelect')?.value;if(!sel)return;let q=[];try{q=await api('/api/care/service-orders?module_key='+encodeURIComponent(sel))}catch(e){return}const theatre=sel==='theatre'&&can('theatre','VIEW')?await api('/api/care/surgery/queue').catch(()=>[]):[];const m=afterHeader(`<div class="panel careNativePanel"><div class="careNativeHead"><div><span class="eyebrow">Patient service requests</span><h3>${cEsc(document.querySelector('#opSelect option:checked')?.textContent||sel)} queue</h3><p>These are clinical requests raised from an active visit file. Completing them updates the same episode.</p></div></div><div class="careQueue">${q.map(o=>`<div class="careQueueRow"><div><b>${cEsc(o.file_no)} · ${cEsc(o.patient_name)}</b><span>${cEsc(o.title)} · ${cEsc(o.status)}${o.invoice?` · ${cEsc(o.invoice.status)}`:''}</span></div><div class="actions">${['ORDERED','SCHEDULED'].includes(o.status)&&can(sel,'EDIT')?`<button class="linkBtn" data-care-start="${o.id}">Start</button>`:''}${['ORDERED','IN_PROGRESS','SCHEDULED'].includes(o.status)&&can(sel,'EDIT')?`<button class="linkBtn" data-care-complete="${o.id}">Complete</button>`:''}<button class="linkBtn" data-care-visit="${o.visit_id}">File</button></div></div>`).join('')||'<div class="empty">No patient service requests.</div>'}</div>${theatre.length?`<div class="careSubsection"><h3>Theatre cases</h3>${theatre.map(s=>`<div class="careQueueRow"><div><b>${cEsc(s.file_no)} · ${cEsc(s.procedure_name)}</b><span>${cEsc(s.status)}${s.theatre_room?` · ${cEsc(s.theatre_room)}`:''}</span></div><button class="linkBtn" data-surgery="${s.id}">Manage theatre case</button></div>`).join('')}</div>`:''}</div>`);bindVisitButtons(m);m.querySelectorAll('[data-care-start]').forEach(b=>b.onclick=async()=>{await api(`/api/care/service-orders/${b.dataset.careStart}/start`,{method:'POST',body:'{}'});cToast('Service started');pages.operations()});m.querySelectorAll('[data-care-complete]').forEach(b=>b.onclick=()=>completeOrder(Number(b.dataset.careComplete)));m.querySelectorAll('[data-surgery]').forEach(b=>b.onclick=()=>manageSurgery(Number(b.dataset.surgery)))});
  function completeOrder(id){const m=cModal('Complete patient service',`<form id="careComplete">${field('Result / completion summary','<textarea name="result_summary" rows="6" required></textarea>')}<div class="modalActions"><button class="primary">Complete service</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();await api(`/api/care/service-orders/${id}/complete`,{method:'POST',body:JSON.stringify({result_summary:new FormData(ev.target).get('result_summary'),status:'COMPLETED'})});m.remove();cToast('Service completed');pages.operations()}}
  async function manageSurgery(id){const rows=await api('/api/care/surgery/queue'),s=rows.find(x=>x.id===id);if(!s)return;const actions=[];if(['REQUESTED','SCHEDULED'].includes(s.status))actions.push('<button class="ghost" data-act="schedule">Schedule</button>');if(s.consent_status!=='SIGNED')actions.push('<button class="ghost" data-act="consent">Record consent</button>');if(['REQUESTED','SCHEDULED'].includes(s.status))actions.push('<button class="ghost" data-act="preop">Pre-op ready</button>');if(['PREOP_READY','SCHEDULED'].includes(s.status))actions.push('<button class="primary" data-act="start">Start theatre</button>');if(s.status==='IN_THEATRE')actions.push('<button class="primary" data-act="complete">Complete operation</button>');if(s.status==='RECOVERY')actions.push('<button class="primary" data-act="recovery">Complete recovery</button>');const m=cModal('Theatre case',`<div class="careVisitHead"><div><span>${cEsc(s.file_no)}</span><h2>${cEsc(s.procedure_name)}</h2><p>${pill(s.status)}</p></div></div><div class="careActionBar">${actions.join('')}</div><div class="panel soft"><p><b>Room:</b> ${cEsc(s.theatre_room||'Not scheduled')}</p><p><b>Consent:</b> ${cEsc(s.consent_status)}</p><p><b>Scheduled:</b> ${dt(s.scheduled_at)}</p></div>`);m.querySelector('[data-act=schedule]')?.addEventListener('click',()=>surgerySchedule(s,m));m.querySelector('[data-act=consent]')?.addEventListener('click',()=>surgeryConsent(s,m));m.querySelector('[data-act=preop]')?.addEventListener('click',()=>surgeryPreop(s,m));m.querySelector('[data-act=start]')?.addEventListener('click',async()=>{await api(`/api/care/surgery/${s.id}/start`,{method:'POST',body:'{}'});m.remove();pages.operations()});m.querySelector('[data-act=complete]')?.addEventListener('click',()=>surgeryComplete(s,m));m.querySelector('[data-act=recovery]')?.addEventListener('click',()=>surgeryRecovery(s,m))}
  function surgerySchedule(s,parent){const m=cModal('Schedule theatre case',`<form>${field('Theatre room','<input name="theatre_room" required>')}${field('Scheduled time','<input name="scheduled_at" type="datetime-local" required>')}<div class="modalActions"><button class="primary">Schedule</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.scheduled_at=new Date(o.scheduled_at).toISOString();o.surgeon_id=null;o.anaesthetist_id=null;await api(`/api/care/surgery/${s.id}/schedule`,{method:'PATCH',body:JSON.stringify(o)});m.remove();parent.remove();pages.operations()}}
  function surgeryConsent(s,parent){const m=cModal('Surgical consent',`<form>${field('Signed by','<input name="signed_by_name" required>')}${field('Relationship','<input name="relationship" value="SELF">')}${field('Notes','<textarea name="notes"></textarea>')}<div class="modalActions"><button class="primary">Record signed consent</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));o.consent_type='SURGERY';o.status='SIGNED';await api(`/api/care/surgery/${s.id}/consent`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();pages.operations()}}
  function surgeryPreop(s,parent){const m=cModal('Pre-operative readiness',`<form>${field('Anaesthesia / pre-op note','<textarea name="anaesthesia_note" rows="4"></textarea>')}<label class="check"><input type="checkbox" name="identity" required> Identity & procedure confirmed</label><label class="check"><input type="checkbox" name="site" required> Site / side confirmed where applicable</label><label class="check"><input type="checkbox" name="allergy" required> Allergies reviewed</label><label class="check"><input type="checkbox" name="blood" required> Blood / investigations reviewed as applicable</label><div class="modalActions"><button class="primary">Mark pre-op ready</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target);const o={checklist:{identity:fd.has('identity'),site:fd.has('site'),allergy:fd.has('allergy'),blood:fd.has('blood')},anaesthesia_note:fd.get('anaesthesia_note')};await api(`/api/care/surgery/${s.id}/preop`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();pages.operations()}}
  function surgeryComplete(s,parent){const m=cModal('Operative note',`<form>${field('Operative note','<textarea name="operative_note" rows="7" required></textarea>')}<div class="modalActions"><button class="primary">Complete operation</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();await api(`/api/care/surgery/${s.id}/complete`,{method:'POST',body:JSON.stringify({operative_note:new FormData(ev.target).get('operative_note')})});m.remove();parent.remove();pages.operations()}}
  function surgeryRecovery(s,parent){const m=cModal('Recovery / destination',`<form>${field('Recovery note','<textarea name="recovery_note" rows="5" required></textarea>')}${field('Destination','<select name="destination"><option>WARD</option><option>ICU</option><option>DOCTOR_REVIEW</option></select>')}<div class="modalActions"><button class="primary">Complete recovery</button></div></form>`);m.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const o=Object.fromEntries(new FormData(ev.target));await api(`/api/care/surgery/${s.id}/recovery`,{method:'POST',body:JSON.stringify(o)});m.remove();parent.remove();pages.operations()}}

  // Extend Workflow Admin without replacing the existing Patient Journey page.
  const oldJourney=pages.journey;
  if(oldJourney){pages.journey=async()=>{await oldJourney();try{if(!document.getElementById('jSettings')||!can('configuration','VIEW'))return;const p=await api('/api/care/policy');const host=document.querySelector('.content');if(!host||document.getElementById('carePolicy'))return;const box=document.createElement('div');box.className='panel careNativePanel';box.id='carePolicy';box.innerHTML=`<span class="eyebrow">Extended care policy</span><h3>Emergency, specialist, theatre & discharge rules</h3><form id="carePolicyForm" class="carePolicyGrid"><label class="check"><input type="checkbox" name="emergency_bypass_payment" ${p.emergency_bypass_payment?'checked':''}> Emergency care can proceed before payment</label><label class="check"><input type="checkbox" name="require_service_payment" ${p.require_service_payment?'checked':''}> Require payment before specialist service</label><label class="check"><input type="checkbox" name="require_surgical_consent" ${p.require_surgical_consent?'checked':''}> Require signed surgical consent</label><label class="check"><input type="checkbox" name="require_preop_checklist" ${p.require_preop_checklist?'checked':''}> Require pre-op checklist</label><label class="check"><input type="checkbox" name="require_inpatient_financial_clearance" ${p.require_inpatient_financial_clearance?'checked':''}> Require inpatient financial clearance</label><label class="check"><input type="checkbox" name="require_discharge_plan" ${p.require_discharge_plan?'checked':''}> Require discharge plan</label><label class="check"><input type="checkbox" name="auto_followup_sms" ${p.auto_followup_sms?'checked':''}> Send follow-up SMS</label>${can('configuration','EDIT')?'<div><button class="primary">Save extended policy</button></div>':''}</form>`;host.appendChild(box);box.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),o={};['emergency_bypass_payment','require_service_payment','require_surgical_consent','require_preop_checklist','require_inpatient_financial_clearance','require_discharge_plan','auto_followup_sms'].forEach(k=>o[k]=fd.has(k));await api('/api/care/policy',{method:'PATCH',body:JSON.stringify(o)});cToast('Extended care policy saved')}}catch(e){console.warn(e)}};}
})();
