/* NEOVAM HMS · Event-driven SMS & Notifications workspace */
(function(){
  const nEsc=typeof esc==='function'?esc:(x=>String(x??''));
  const eventRows=[
    ['appointment_confirmations','Appointment confirmations','Confirmation/cancellation messages when an appointment changes'],
    ['appointment_reminders','Appointment reminders','Automatic reminder before the appointment'],
    ['lab_results','Lab results notifications','Results-ready notice with assigned doctor, room and queue position'],
    ['prescription_medication','Prescription & medication','Prescription-ready, medication and refill reminders'],
    ['followup_reminders','Follow-up reminders','Confirmation and reminder for booked follow-up care'],
    ['health_campaigns','Health campaigns','Screening, vaccination, blood donation and public-health campaigns'],
    ['hospital_promotions','Hospital promotions','New services, specialist clinics, packages and approved offers'],
    ['satisfaction_surveys','Patient satisfaction','Post-visit survey/feedback request'],
    ['billing_payments','Payment & billing','New bill and payment confirmation messages'],
    ['emergency_notifications','Emergency notifications','Urgent service, closure or public-health notices'],
    ['staff_communication','Staff communication','Operational notices to staff with registered phone numbers'],
    ['queue_notifications','Queue notifications','Patient queue-position updates for doctor rooms'],
    ['otp_sms','OTP / verification','One-time verification codes for supported HMS workflows'],
  ];
  function fmt(v){if(!v)return '—';try{return new Date(v).toLocaleString()}catch(_){return String(v)}}
  function nBadge(v){return typeof badge==='function'?badge(v):`<span>${nEsc(v)}</span>`}
  function toggleRow(key,title,desc,on){return `<label class="moduleRow" style="cursor:pointer"><div><b>${nEsc(title)}</b><small>${nEsc(desc)}</small></div><input type="checkbox" name="${key}" ${on?'checked':''}></label>`}
  function gatewayCard(g){const configured=!!g?.configured;return `<div class="panel"><div class="sectionHead"><div><span class="eyebrow">Delivery gateway</span><h3>NEOVAM SMS Gateway</h3></div>${nBadge(configured?'CONFIGURED':'NOT CONFIGURED')}</div><p class="muted">${configured?`Gateway: ${nEsc(g.gateway_origin||'configured')} · Client: ${nEsc(g.client_id||'—')}`:'Configure HMS_SMS_GATEWAY_URL, client ID and shared secret in the server environment. Clinical workflows continue even when SMS delivery is unavailable.'}</p></div>`}
  function settingsPanel(s){return `<div class="panel"><div class="sectionHead"><div><span class="eyebrow">Event rules</span><h3>Automatic & campaign SMS</h3></div><label class="check"><input id="nMaster" type="checkbox" ${s.enabled?'checked':''}> SMS enabled</label></div><form id="nSettings"><div class="moduleGroups"><div class="panel soft">${eventRows.map(([k,t,d])=>toggleRow(k,t,d,s[k])).join('')}</div></div><div class="formGrid" style="margin-top:14px">${field('Appointment reminder lead (hours)',`<input name="appointment_reminder_hours" type="number" min="1" max="168" value="${s.appointment_reminder_hours}">`)}${field('Follow-up reminder lead (hours)',`<input name="followup_reminder_hours" type="number" min="1" max="168" value="${s.followup_reminder_hours}">`)}${field('Medication reminder days',`<input name="medication_reminder_days" type="number" min="0" max="14" value="${s.medication_reminder_days}">`)}${field('Survey delay (hours)',`<input name="satisfaction_delay_hours" type="number" min="1" max="168" value="${s.satisfaction_delay_hours}">`)}${field('Queue notify threshold',`<input name="queue_notify_threshold" type="number" min="1" max="10" value="${s.queue_notify_threshold}">`)}${field('Timezone',`<input name="timezone_name" value="${nEsc(s.timezone_name||'Africa/Dar_es_Salaam')}">`)}${field('Survey URL (optional)',`<input name="survey_url" type="url" value="${nEsc(s.survey_url||'')}" placeholder="https://...">`)}<div class="modalActions span2"><button class="primary">Save notification settings</button></div></div></form></div>`}
  function campaignPanel(){return `<div class="panel"><div class="sectionHead"><div><span class="eyebrow">Broadcasts</span><h3>Campaign / emergency / staff message</h3></div></div><form id="nCampaign" class="formGrid">${field('Type','<select name="campaign_type"><option value="HEALTH_CAMPAIGN">Health campaign</option><option value="HOSPITAL_PROMOTION">Hospital promotion</option><option value="EMERGENCY_NOTIFICATION">Emergency notification</option><option value="STAFF_COMMUNICATION">Staff communication</option></select>')}${field('Audience','<select name="audience"><option value="PATIENTS">Patients</option><option value="STAFF">Staff</option><option value="BOTH">Patients + staff</option></select>')}${field('Title','<input name="title" required maxlength="160" placeholder="e.g. Free diabetes screening">')}${field('Schedule (optional)','<input name="scheduled_at" type="datetime-local">')}${field('Message','<textarea name="message" rows="4" maxlength="700" required placeholder="Keep messages clear and avoid sensitive clinical details."></textarea>')}<div class="notice">Health campaigns and promotions go only to patients who opted into marketing SMS. Emergency and service messages use operational SMS consent.</div><div class="modalActions span2"><button class="primary">Schedule / send</button></div></form></div>`}
  function refillPanel(){return `<div class="panel"><div class="sectionHead"><div><span class="eyebrow">Medication</span><h3>Manual refill reminder</h3></div></div><form id="nRefill" class="formGrid">${field('Patient ID','<input name="patient_id" type="number" min="1" required>')}${field('Visit ID (optional)','<input name="visit_id" type="number" min="1">')}${field('Send at','<input name="send_at" type="datetime-local" required>')}${field('Custom message (optional)','<textarea name="message" rows="3" maxlength="700"></textarea>')}<div class="modalActions span2"><button class="primary">Schedule refill reminder</button></div></form></div>`}
  function tables(outbox,jobs,campaigns){return `<div class="panel"><div class="sectionHead"><div><span class="eyebrow">Delivery</span><h3>SMS outbox</h3></div><div class="actions"><button class="ghost" id="nProcessDue">Process due</button><button class="ghost" id="nRetry">Retry queued/failed</button></div></div>${table(['Time','Event','Phone','Message','Status'],outbox.slice(0,80).map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${nEsc(x.event_type)}</td><td>${nEsc(x.phone)}</td><td>${nEsc(x.message)}</td><td>${nBadge(x.status)}</td></tr>`))}</div><div class="journeySplit"><div class="panel"><div class="sectionHead"><h3>Scheduled jobs</h3><span class="muted">${jobs.length}</span></div>${table(['Send at','Event','Phone','Status'],jobs.slice(0,50).map(x=>`<tr><td>${fmt(x.send_at)}</td><td>${nEsc(x.event_type)}</td><td>${nEsc(x.phone)}</td><td>${nBadge(x.status)}</td></tr>`))}</div><div class="panel"><div class="sectionHead"><h3>Campaign history</h3><span class="muted">${campaigns.length}</span></div>${table(['When','Type','Audience','Recipients','Status'],campaigns.slice(0,50).map(x=>`<tr><td>${fmt(x.scheduled_at)}</td><td>${nEsc(x.campaign_type)}</td><td>${nEsc(x.audience)}</td><td>${x.recipient_count}</td><td>${nBadge(x.status)}</td></tr>`))}</div></div>`}
  pages.notifications=async()=>{
    try{
      const [s,outbox,jobs,campaigns,gateway]=await Promise.all([
        api('/api/notifications/settings'),api('/api/notifications/outbox'),api('/api/notifications/jobs'),api('/api/notifications/campaigns'),api('/api/journey/sms-gateway/status').catch(()=>({configured:false}))
      ]);
      shell(header('SMS & Notifications','Event-driven patient and staff communication through the NEOVAM SMS Gateway')+gatewayCard(gateway)+`<div class="journeySplit">${settingsPanel(s)}${campaignPanel()+refillPanel()}</div>`+tables(outbox,jobs,campaigns));
      bind(s);
    }catch(e){shell(header('SMS & Notifications','Notification configuration')+`<div class="banner banner-danger"><div class="bannerTitle"><b>Could not load notifications</b><span>${nEsc(e.message)}</span></div></div>`)}
  };
  function bind(s){
    document.getElementById('nSettings')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),o={enabled:document.getElementById('nMaster').checked};eventRows.forEach(([k])=>o[k]=fd.has(k));['appointment_reminder_hours','followup_reminder_hours','medication_reminder_days','satisfaction_delay_hours','queue_notify_threshold'].forEach(k=>o[k]=Number(fd.get(k)));o.timezone_name=fd.get('timezone_name');o.survey_url=fd.get('survey_url')||null;try{await api('/api/notifications/settings',{method:'PATCH',body:JSON.stringify(o)});toast('Notification settings saved');pages.notifications()}catch(x){toast(x.message)}});
    document.getElementById('nCampaign')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),o=Object.fromEntries(fd);if(!o.scheduled_at)delete o.scheduled_at;else o.scheduled_at=new Date(o.scheduled_at).toISOString();try{const r=await api('/api/notifications/campaigns',{method:'POST',body:JSON.stringify(o)});toast(`${r.recipient_count} recipient(s) queued`);pages.notifications()}catch(x){toast(x.message)}});
    document.getElementById('nRefill')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),o={patient_id:Number(fd.get('patient_id')),visit_id:fd.get('visit_id')?Number(fd.get('visit_id')):null,send_at:new Date(fd.get('send_at')).toISOString(),message:fd.get('message')||null};try{await api('/api/notifications/refill-reminders',{method:'POST',body:JSON.stringify(o)});toast('Refill reminder scheduled');pages.notifications()}catch(x){toast(x.message)}});
    document.getElementById('nProcessDue')?.addEventListener('click',async()=>{try{const r=await api('/api/notifications/process-due',{method:'POST',body:'{}'});toast(`${r.processed} scheduled message(s) processed`);pages.notifications()}catch(x){toast(x.message)}});
    document.getElementById('nRetry')?.addEventListener('click',async()=>{try{const r=await api('/api/journey/sms-outbox/retry',{method:'POST',body:JSON.stringify({ids:null})});toast(`${r.processed} outbox message(s) processed`);pages.notifications()}catch(x){toast(x.message)}});
  }
})();
